# Generated by Django 6.0.6 on 2026-06-17 15:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='الاسم')),
                ('phone', models.CharField(max_length=20, unique=True, verbose_name='رقم الهاتف')),
                ('contact_type', models.CharField(choices=[('customer', 'عميل'), ('supplier', 'مورد شركات'), ('used_seller', 'بائع أجهزة مستعملة (فرد)')], max_length=20, verbose_name='نوع جهة الاتصال')),
                ('national_id', models.CharField(blank=True, max_length=14, null=True, verbose_name='الرقم القومي')),
                ('address', models.TextField(blank=True, null=True, verbose_name='العنوان')),
            ],
        ),
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='بند المصروف')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='اسم الصنف')),
                ('barcode_qr', models.CharField(max_length=100, unique=True, verbose_name='الباركود / QR')),
                ('product_type', models.CharField(choices=[('phone', 'موبايل'), ('accessory', 'إكسسوار'), ('spare_part', 'قطعة غيار')], max_length=20, verbose_name='نوع الصنف')),
                ('average_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='متوسط التكلفة')),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='سعر البيع')),
                ('requires_imei', models.BooleanField(default=False, verbose_name='يتطلب سيريال/IMEI')),
            ],
        ),
        migrations.CreateModel(
            name='StoreSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(max_length=255, verbose_name='اسم المحل')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='store_assets/', verbose_name='شعار المحل')),
                ('receipt_header', models.TextField(blank=True, verbose_name='ترويسة الفاتورة')),
                ('receipt_footer', models.TextField(blank=True, verbose_name='تذييل الفاتورة')),
                ('whatsapp_api_key', models.CharField(blank=True, max_length=255, null=True, verbose_name='مفتاح API الواتساب')),
                ('sms_api_key', models.CharField(blank=True, max_length=255, null=True, verbose_name='مفتاح API الرسائل النصية')),
            ],
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم المخزن / الفرع')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
            ],
        ),
        migrations.CreateModel(
            name='CashShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('opening_balance', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='رصيد البداية')),
                ('expected_closing_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('actual_cash', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('status', models.CharField(choices=[('open', 'مفتوحة'), ('closed', 'مغلقة')], default='open', max_length=20)),
                ('cashier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='الكاشير')),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imei', models.CharField(max_length=50, unique=True, verbose_name='السيريال/IMEI')),
                ('condition', models.CharField(choices=[('new', 'جديد'), ('used', 'مستعمل')], max_length=20, verbose_name='الحالة')),
                ('is_sold', models.BooleanField(default=False, verbose_name='مباع؟')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='تكلفة الشراء')),
                ('purchased_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='erp.contact', verbose_name='تم الشراء من (للمستعمل)')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.product', verbose_name='الموديل/الصنف')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.warehouse', verbose_name='المخزن الحالي')),
            ],
        ),
        migrations.CreateModel(
            name='DeviceAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment_type', models.CharField(choices=[('id_front', 'صورة البطاقة - وجه'), ('id_back', 'صورة البطاقة - ظهر'), ('contract', 'عقد مبايعة / إقرار تنازل'), ('device_condition', 'صورة لحالة الجهاز'), ('other', 'أخرى')], max_length=20, verbose_name='نوع المرفق')),
                ('image', models.ImageField(upload_to='used_devices_docs/%Y/%m/', verbose_name='الصورة')),
                ('notes', models.CharField(blank=True, max_length=255, null=True, verbose_name='ملاحظات')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='erp.device')),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='erp.cashshift')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp.expensecategory')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_date', models.DateTimeField(auto_now_add=True)),
                ('supplier_invoice_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='رقم فاتورة المورد')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='الإجمالي')),
                ('discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='الخصم')),
                ('deduction_addition_tax', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='ضريبة الخصم والإضافة')),
                ('net_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='الصافي للدفع')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='مستلم البضاعة')),
                ('supplier', models.ForeignKey(limit_choices_to={'contact_type': 'supplier'}, on_delete=django.db.models.deletion.PROTECT, to='erp.contact', verbose_name='المورد')),
            ],
        ),
        migrations.CreateModel(
            name='RepairTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_model', models.CharField(max_length=100, verbose_name='موديل الجهاز')),
                ('device_imei', models.CharField(blank=True, max_length=50, null=True)),
                ('issue_description', models.TextField(verbose_name='وصف العطل')),
                ('status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('in_progress', 'جاري العمل'), ('waiting_parts', 'في انتظار قطع الغيار'), ('done', 'جاهز للتسليم'), ('delivered', 'تم التسليم')], default='pending', max_length=20)),
                ('estimated_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('labor_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='مصنعية')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.contact')),
                ('technician', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('whatsapp', 'واتساب'), ('sms', 'SMS')], max_length=20)),
                ('message_body', models.TextField()),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='sent', max_length=20)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.contact')),
                ('ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='erp.repairticket')),
            ],
        ),
        migrations.CreateModel(
            name='SaleInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('trade_in_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('net_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='الصافي')),
                ('cashier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp.contact')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp.cashshift')),
                ('traded_in_device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='traded_in_invoice', to='erp.device')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(choices=[('cash', 'نقدي'), ('visa', 'فيزا'), ('wallet', 'محفظة إلكترونية')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='erp.saleinvoice')),
            ],
        ),
        migrations.CreateModel(
            name='StockTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'قيد النقل'), ('completed', 'تم الاستلام')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_created', to=settings.AUTH_USER_MODEL)),
                ('from_warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_out', to='erp.warehouse', verbose_name='من مخزن')),
                ('to_warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_in', to='erp.warehouse', verbose_name='إلى مخزن')),
            ],
        ),
        migrations.CreateModel(
            name='StockTransferItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='erp.device')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp.product')),
                ('transfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='erp.stocktransfer')),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0, verbose_name='الكمية')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.product', verbose_name='الصنف')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.warehouse', verbose_name='المخزن')),
            ],
        ),
        migrations.CreateModel(
            name='SaleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='erp.device')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='erp.saleinvoice')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp.product')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp.warehouse')),
            ],
        ),
        migrations.CreateModel(
            name='RepairPartUsed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp.product')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts_used', to='erp.repairticket')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp.warehouse')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('imei_list', models.TextField(blank=True, help_text='للسيريالات مفصولة بفاصلة', null=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='erp.purchaseinvoice')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp.product')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp.warehouse')),
            ],
        ),
        migrations.CreateModel(
            name='Warranty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration_days', models.IntegerField(default=14)),
                ('start_date', models.DateField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.contact')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.device')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.saleinvoice')),
            ],
        ),
    ]
