# Generated by Django 6.0.6 on 2026-06-17 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='imei2',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='السيريال 2/IMEI 2'),
        ),
        migrations.AlterField(
            model_name='device',
            name='imei',
            field=models.CharField(max_length=50, unique=True, verbose_name='السيريال/IMEI 1'),
        ),
    ]
