# Generated by Django 6.0.6 on 2026-06-17 16:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0002_device_imei2_alter_device_imei'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='national_id',
            field=models.CharField(blank=True, max_length=14, null=True, validators=[django.core.validators.RegexValidator(message='الرقم القومي يجب أن يتكون من 14 رقماً فقط.', regex='^\\d{14}$')], verbose_name='الرقم القومي'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='رقم الهاتف يجب أن يتكون من 11 رقماً فقط.', regex='^\\d{11}$')], verbose_name='رقم الهاتف'),
        ),
    ]
