# Generated by Django 6.0.6 on 2026-06-17 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0003_alter_contact_national_id_alter_contact_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deviceattachment',
            name='attachment_type',
            field=models.CharField(blank=True, choices=[('id_front', 'صورة البطاقة - وجه'), ('id_back', 'صورة البطاقة - ظهر'), ('contract', 'عقد مبايعة / إقرار تنازل'), ('device_condition', 'صورة لحالة الجهاز'), ('other', 'أخرى')], max_length=20, null=True, verbose_name='نوع المرفق'),
        ),
        migrations.AlterField(
            model_name='deviceattachment',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='used_devices_docs/%Y/%m/', verbose_name='الصورة'),
        ),
    ]
