# Generated by Django 6.0.6 on 2026-06-17 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0004_alter_deviceattachment_attachment_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='has_box',
            field=models.BooleanField(default=False, verbose_name='يوجد كرتونة'),
        ),
        migrations.AddField(
            model_name='device',
            name='has_charger',
            field=models.BooleanField(default=False, verbose_name='يوجد شاحن'),
        ),
        migrations.AddField(
            model_name='device',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='ملاحظات الجهاز'),
        ),
        migrations.AddField(
            model_name='device',
            name='ram',
            field=models.CharField(blank=True, choices=[('3', '3 رام'), ('4', '4 رام'), ('6', '6 رام'), ('8', '8 رام'), ('12', '12 رام'), ('other', 'أخرى')], max_length=20, null=True, verbose_name='الرام'),
        ),
        migrations.AddField(
            model_name='device',
            name='storage',
            field=models.CharField(blank=True, choices=[('128', '128 جيجا'), ('256', '256 جيجا'), ('512', '512 جيجا'), ('1tb', '1 تيرا'), ('other', 'أخرى')], max_length=20, null=True, verbose_name='المساحة'),
        ),
        migrations.AddField(
            model_name='device',
            name='used_status',
            field=models.CharField(blank=True, choices=[('like_new', 'كسر زيرو'), ('good_condition', 'مستعمل بحالة جيدة'), ('other', 'أخرى')], max_length=20, null=True, verbose_name='حالة الجهاز المستعمل'),
        ),
    ]
