# Generated by Django 6.0.6 on 2026-06-17 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0005_device_has_box_device_has_charger_device_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاريخ الإدخال'),
        ),
        migrations.AddField(
            model_name='device',
            name='is_tax_paid',
            field=models.BooleanField(default=False, verbose_name='خالص الضريبة'),
        ),
        migrations.AlterField(
            model_name='device',
            name='storage',
            field=models.CharField(blank=True, choices=[('128', '128 جيجا'), ('256', '256 جيجا'), ('512', '512 جيجا'), ('1gb', '1 جيجا'), ('1tb', '1 تيرا'), ('other', 'أخرى')], max_length=20, null=True, verbose_name='المساحة'),
        ),
    ]
