# Generated by Django 5.1 on 2026-06-18 09:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0006_device_created_at_device_is_tax_paid_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cashshift',
            options={'verbose_name': 'وردية خزينة', 'verbose_name_plural': 'ورديات الخزينة'},
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'جهة اتصال', 'verbose_name_plural': 'جهات الاتصال'},
        ),
        migrations.AlterModelOptions(
            name='device',
            options={'verbose_name': 'جهاز موبايل', 'verbose_name_plural': 'الأجهزة'},
        ),
        migrations.AlterModelOptions(
            name='deviceattachment',
            options={'verbose_name': 'مرفق جهاز', 'verbose_name_plural': 'مرفقات الأجهزة'},
        ),
        migrations.AlterModelOptions(
            name='expense',
            options={'verbose_name': 'مصروف تشغيلي', 'verbose_name_plural': 'المصروفات التشغيلية'},
        ),
        migrations.AlterModelOptions(
            name='expensecategory',
            options={'verbose_name': 'تصنيف مصروف', 'verbose_name_plural': 'تصنيفات المصروفات'},
        ),
        migrations.AlterModelOptions(
            name='notificationlog',
            options={'verbose_name': 'سجل إشعار', 'verbose_name_plural': 'سجلات الإشعارات'},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'verbose_name': 'دفعة مالية', 'verbose_name_plural': 'الدفعات المالية'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'صنف / منتج', 'verbose_name_plural': 'دليل الأصناف والمنتجات'},
        ),
        migrations.AlterModelOptions(
            name='purchaseinvoice',
            options={'verbose_name': 'فاتورة مشتريات', 'verbose_name_plural': 'فواتير المشتريات'},
        ),
        migrations.AlterModelOptions(
            name='purchaseitem',
            options={'verbose_name': 'بند مشتريات', 'verbose_name_plural': 'بنود المشتريات'},
        ),
        migrations.AlterModelOptions(
            name='repairpartused',
            options={'verbose_name': 'قطعة غيار مستهلكة', 'verbose_name_plural': 'قطع الغيار المستهلكة في الصيانة'},
        ),
        migrations.AlterModelOptions(
            name='repairticket',
            options={'verbose_name': 'تذكرة صيانة', 'verbose_name_plural': 'تذاكر الصيانة'},
        ),
        migrations.AlterModelOptions(
            name='saleinvoice',
            options={'verbose_name': 'فاتورة مبيعات', 'verbose_name_plural': 'فواتير المبيعات'},
        ),
        migrations.AlterModelOptions(
            name='saleitem',
            options={'verbose_name': 'بند مبيعات', 'verbose_name_plural': 'بنود المبيعات'},
        ),
        migrations.AlterModelOptions(
            name='stock',
            options={'verbose_name': 'كمية مخزون', 'verbose_name_plural': 'كميات المخزون'},
        ),
        migrations.AlterModelOptions(
            name='stocktransfer',
            options={'verbose_name': 'حركة تحويل مخزن', 'verbose_name_plural': 'حركات تحويل المخازن'},
        ),
        migrations.AlterModelOptions(
            name='stocktransferitem',
            options={'verbose_name': 'بند تحويل مخزن', 'verbose_name_plural': 'بنود تحويل المخازن'},
        ),
        migrations.AlterModelOptions(
            name='storesetting',
            options={'verbose_name': 'إعدادات المتجر', 'verbose_name_plural': 'إعدادات المتجر'},
        ),
        migrations.AlterModelOptions(
            name='warehouse',
            options={'verbose_name': 'مخزن / فرع', 'verbose_name_plural': 'المخازن والفروع'},
        ),
        migrations.AlterModelOptions(
            name='warranty',
            options={'verbose_name': 'ضمان جهاز', 'verbose_name_plural': 'الضمانات'},
        ),
        migrations.AlterField(
            model_name='cashshift',
            name='actual_cash',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='الرصيد الفعلي المسلم'),
        ),
        migrations.AlterField(
            model_name='cashshift',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='وقت إغلاق الوردية'),
        ),
        migrations.AlterField(
            model_name='cashshift',
            name='expected_closing_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='الرصيد النقدي المتوقع'),
        ),
        migrations.AlterField(
            model_name='cashshift',
            name='start_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='وقت فتح الوردية'),
        ),
        migrations.AlterField(
            model_name='cashshift',
            name='status',
            field=models.CharField(choices=[('open', 'مفتوحة'), ('closed', 'مغلقة')], default='open', max_length=20, verbose_name='حالة الوردية'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='المبلغ'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp.expensecategory', verbose_name='بند المصروف'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='التفاصيل/الوصف'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='shift',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='erp.cashshift', verbose_name='الوردية'),
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.contact', verbose_name='العميل'),
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='message_body',
            field=models.TextField(verbose_name='محتوى الرسالة'),
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='notification_type',
            field=models.CharField(choices=[('whatsapp', 'واتساب'), ('sms', 'SMS')], max_length=20, verbose_name='نوع الإشعار'),
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='sent_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='وقت الإرسال'),
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='status',
            field=models.CharField(default='sent', max_length=20, verbose_name='الحالة'),
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='ticket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='erp.repairticket', verbose_name='تذكرة الصيانة'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='المبلغ'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='erp.saleinvoice', verbose_name='الفاتورة'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'نقدي'), ('visa', 'فيزا'), ('wallet', 'محفظة إلكترونية')], max_length=20, verbose_name='طريقة الدفع'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='رقم المعاملة'),
        ),
        migrations.AlterField(
            model_name='purchaseinvoice',
            name='invoice_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الفاتورة'),
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='imei_list',
            field=models.TextField(blank=True, help_text='للسيريالات مفصولة بفاصلة', null=True, verbose_name='قائمة السيريالات/IMEI'),
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='erp.purchaseinvoice', verbose_name='فاتورة الشراء'),
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp.product', verbose_name='الصنف'),
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='quantity',
            field=models.IntegerField(verbose_name='الكمية'),
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='unit_cost',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='تكلفة الوحدة'),
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp.warehouse', verbose_name='المخزن'),
        ),
        migrations.AlterField(
            model_name='repairpartused',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='سعر البيع'),
        ),
        migrations.AlterField(
            model_name='repairpartused',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp.product', verbose_name='قطعة الغيار'),
        ),
        migrations.AlterField(
            model_name='repairpartused',
            name='quantity',
            field=models.IntegerField(default=1, verbose_name='الكمية'),
        ),
        migrations.AlterField(
            model_name='repairpartused',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts_used', to='erp.repairticket', verbose_name='التذكرة'),
        ),
        migrations.AlterField(
            model_name='repairpartused',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp.warehouse', verbose_name='مخزن السحب'),
        ),
        migrations.AlterField(
            model_name='repairticket',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.contact', verbose_name='العميل'),
        ),
        migrations.AlterField(
            model_name='repairticket',
            name='device_imei',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='السيريال/IMEI'),
        ),
        migrations.AlterField(
            model_name='repairticket',
            name='estimated_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='التكلفة التقديرية'),
        ),
        migrations.AlterField(
            model_name='repairticket',
            name='status',
            field=models.CharField(choices=[('pending', 'قيد الانتظار'), ('in_progress', 'جاري العمل'), ('waiting_parts', 'في انتظار قطع الغيار'), ('done', 'جاهز للتسليم'), ('delivered', 'تم التسليم')], default='pending', max_length=20, verbose_name='حالة التذكرة'),
        ),
        migrations.AlterField(
            model_name='repairticket',
            name='technician',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='الفني المختص'),
        ),
        migrations.AlterField(
            model_name='saleinvoice',
            name='cashier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='الكاشير'),
        ),
        migrations.AlterField(
            model_name='saleinvoice',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp.contact', verbose_name='العميل'),
        ),
        migrations.AlterField(
            model_name='saleinvoice',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الفاتورة'),
        ),
        migrations.AlterField(
            model_name='saleinvoice',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='الخصم'),
        ),
        migrations.AlterField(
            model_name='saleinvoice',
            name='shift',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp.cashshift', verbose_name='الوردية'),
        ),
        migrations.AlterField(
            model_name='saleinvoice',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='الإجمالي'),
        ),
        migrations.AlterField(
            model_name='saleinvoice',
            name='trade_in_value',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='قيمة الاستبدال'),
        ),
        migrations.AlterField(
            model_name='saleinvoice',
            name='traded_in_device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='traded_in_invoice', to='erp.device', verbose_name='الجهاز المستبدل'),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='erp.device', verbose_name='جهاز موبايل'),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='erp.saleinvoice', verbose_name='الفاتورة'),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp.product', verbose_name='الصنف'),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='quantity',
            field=models.IntegerField(default=1, verbose_name='الكمية'),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='سعر الوحدة'),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp.warehouse', verbose_name='المخزن'),
        ),
        migrations.AlterField(
            model_name='stocktransfer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ التحويل'),
        ),
        migrations.AlterField(
            model_name='stocktransfer',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_created', to=settings.AUTH_USER_MODEL, verbose_name='منشئ التحويل'),
        ),
        migrations.AlterField(
            model_name='stocktransfer',
            name='status',
            field=models.CharField(choices=[('pending', 'قيد النقل'), ('completed', 'تم الاستلام')], default='pending', max_length=20, verbose_name='حالة التحويل'),
        ),
        migrations.AlterField(
            model_name='stocktransferitem',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='erp.device', verbose_name='جهاز موبايل'),
        ),
        migrations.AlterField(
            model_name='stocktransferitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp.product', verbose_name='الصنف'),
        ),
        migrations.AlterField(
            model_name='stocktransferitem',
            name='quantity',
            field=models.IntegerField(default=1, verbose_name='الكمية'),
        ),
        migrations.AlterField(
            model_name='stocktransferitem',
            name='transfer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='erp.stocktransfer', verbose_name='حركة التحويل'),
        ),
        migrations.AlterField(
            model_name='warranty',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.contact', verbose_name='العميل'),
        ),
        migrations.AlterField(
            model_name='warranty',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.device', verbose_name='الجهاز'),
        ),
        migrations.AlterField(
            model_name='warranty',
            name='duration_days',
            field=models.IntegerField(default=14, verbose_name='مدة الضمان (بالأيام)'),
        ),
        migrations.AlterField(
            model_name='warranty',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.saleinvoice', verbose_name='فاتورة البيع'),
        ),
        migrations.AlterField(
            model_name='warranty',
            name='start_date',
            field=models.DateField(auto_now_add=True, verbose_name='تاريخ بدء الضمان'),
        ),
    ]
