# Generated by Django 6.0.6 on 2026-06-19 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0008_seed_groups_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseitem',
            name='is_tax_paid',
            field=models.BooleanField(default=False, verbose_name='خالص الضريبة'),
        ),
        migrations.AddField(
            model_name='purchaseitem',
            name='ram',
            field=models.CharField(blank=True, choices=[('3', '3 رام'), ('4', '4 رام'), ('6', '6 رام'), ('8', '8 رام'), ('12', '12 رام'), ('other', 'أخرى')], max_length=20, null=True, verbose_name='الرام'),
        ),
        migrations.AddField(
            model_name='purchaseitem',
            name='storage',
            field=models.CharField(blank=True, choices=[('128', '128 جيجا'), ('256', '256 جيجا'), ('512', '512 جيجا'), ('1gb', '1 جيجا'), ('1tb', '1 تيرا'), ('other', 'أخرى')], max_length=20, null=True, verbose_name='المساحة'),
        ),
    ]
