# Generated by Django 6.0.6 on 2026-06-19 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0009_purchaseitem_is_tax_paid_purchaseitem_ram_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseinvoice',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='المبلغ المدفوع'),
        ),
        migrations.AddField(
            model_name='purchaseinvoice',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'نقدي (كاش)'), ('credit', 'آجل بالكامل'), ('partial', 'مسدد جزئياً')], default='cash', max_length=20, verbose_name='طريقة الدفع'),
        ),
    ]
