# Generated by Django 6.0.6 on 2026-06-19 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0011_repairticket_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whatsapp_enabled', models.BooleanField(default=False, help_text='فعّل فقط بعد مسح QR Code وربط الهاتف بالسيرفر.', verbose_name='تفعيل إشعارات الواتساب')),
                ('sender_phone', models.CharField(blank=True, help_text='الصيغة الدولية مثال: +201012345678', max_length=20, null=True, verbose_name='رقم الواتساب المرسل')),
                ('branch_name', models.CharField(default='المحل', help_text='سيظهر في نصوص الرسائل تلقائياً.', max_length=100, verbose_name='اسم الفرع / المحل')),
                ('delay_min_seconds', models.PositiveSmallIntegerField(default=15, verbose_name='الحد الادنى للتاخير (ثانية)')),
                ('delay_max_seconds', models.PositiveSmallIntegerField(default=45, verbose_name='الحد الاقصى للتاخير (ثانية)')),
                ('msg_pending_enabled', models.BooleanField(default=False, verbose_name='ارسال عند: قيد الانتظار')),
                ('msg_pending', models.TextField(default='اهلاً {customer_name}، تم استلام جهازك {device_model} في {branch_name}. رقم تذكرتك: #{ticket_id}', verbose_name='قالب: قيد الانتظار')),
                ('msg_in_progress_enabled', models.BooleanField(default=True, verbose_name='ارسال عند: جاري العمل')),
                ('msg_in_progress', models.TextField(default='اهلاً {customer_name}، بدأ فريقنا العمل على جهازك {device_model}. رقم التذكرة: #{ticket_id} — {branch_name}', verbose_name='قالب: جاري العمل')),
                ('msg_waiting_parts_enabled', models.BooleanField(default=True, verbose_name='ارسال عند: انتظار قطع الغيار')),
                ('msg_waiting_parts', models.TextField(default='اهلاً {customer_name}، جهازك {device_model} يحتاج قطعة غيار قيد التوفير. سنبلغك فور الانتهاء. رقم التذكرة: #{ticket_id}', verbose_name='قالب: انتظار قطع الغيار')),
                ('msg_done_enabled', models.BooleanField(default=True, verbose_name='ارسال عند: جاهز للتسليم')),
                ('msg_done', models.TextField(default='جهازك {device_model} جاهز للاستلام من {branch_name}! رقم التذكرة: #{ticket_id}. في انتظارك {customer_name}', verbose_name='قالب: جاهز للتسليم')),
                ('msg_delivered_enabled', models.BooleanField(default=False, verbose_name='ارسال عند: تم التسليم')),
                ('msg_delivered', models.TextField(default='شكراً {customer_name} على ثقتك في {branch_name}. رقم التذكرة: #{ticket_id}', verbose_name='قالب: تم التسليم')),
            ],
            options={
                'verbose_name': 'اعدادات الاشعارات',
                'verbose_name_plural': 'اعدادات الاشعارات',
            },
        ),
        migrations.AlterModelOptions(
            name='notificationlog',
            options={'ordering': ['-sent_at'], 'verbose_name': 'سجل إشعار', 'verbose_name_plural': 'سجلات الإشعارات'},
        ),
        migrations.AddField(
            model_name='notificationlog',
            name='error_message',
            field=models.TextField(blank=True, null=True, verbose_name='رسالة الخطأ'),
        ),
        migrations.AddField(
            model_name='notificationlog',
            name='retry_count',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='عدد المحاولات'),
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='notification_type',
            field=models.CharField(choices=[('whatsapp', 'واتساب'), ('sms', 'SMS')], default='whatsapp', max_length=20, verbose_name='نوع الإشعار'),
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='status',
            field=models.CharField(choices=[('queued', 'في الانتظار'), ('sent', 'تم الإرسال'), ('failed', 'فشل الإرسال'), ('skipped', 'تم التخطي (مغلق)')], default='queued', max_length=20, verbose_name='الحالة'),
        ),
    ]
