# Generated by Django 6.0.6 on 2026-06-23 10:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0012_add_notification_settings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Treasury',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم الخزينة')),
                ('opening_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='رصيد أول المدة')),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='الرصيد الحالي')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشطة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='treasuries', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم المسؤول')),
            ],
            options={
                'verbose_name': 'خزينة',
                'verbose_name_plural': 'الخزن',
            },
        ),
    ]
