# Generated by Django 6.0.6 on 2026-06-23 11:09

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0013_treasury'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cashshift',
            options={'verbose_name': 'ظˆط±ط¯ظٹط© ط®ط²ظٹظ†ط©', 'verbose_name_plural': 'ظˆط±ط¯ظٹط§طھ ط§ظ„ط®ط²ظٹظ†ط©'},
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'ط¬ظ‡ط© ط§طھطµط§ظ„', 'verbose_name_plural': 'ط¬ظ‡ط§طھ ط§ظ„ط§طھطµط§ظ„'},
        ),
        migrations.AlterModelOptions(
            name='device',
            options={'verbose_name': 'ط¬ظ‡ط§ط² ظ…ظˆط¨ط§ظٹظ„', 'verbose_name_plural': 'ط§ظ„ط£ط¬ظ‡ط²ط©'},
        ),
        migrations.AlterModelOptions(
            name='deviceattachment',
            options={'verbose_name': 'ظ…ط±ظپظ‚ ط¬ظ‡ط§ط²', 'verbose_name_plural': 'ظ…ط±ظپظ‚ط§طھ ط§ظ„ط£ط¬ظ‡ط²ط©'},
        ),
        migrations.AlterModelOptions(
            name='expense',
            options={'verbose_name': 'ظ…طµط±ظˆظپ طھط´ط؛ظٹظ„ظٹ', 'verbose_name_plural': 'ط§ظ„ظ…طµط±ظˆظپط§طھ ط§ظ„طھط´ط؛ظٹظ„ظٹط©'},
        ),
        migrations.AlterModelOptions(
            name='expensecategory',
            options={'verbose_name': 'طھطµظ†ظٹظپ ظ…طµط±ظˆظپ', 'verbose_name_plural': 'طھطµظ†ظٹظپط§طھ ط§ظ„ظ…طµط±ظˆظپط§طھ'},
        ),
        migrations.AlterModelOptions(
            name='notificationlog',
            options={'ordering': ['-sent_at'], 'verbose_name': 'ط³ط¬ظ„ ط¥ط´ط¹ط§ط±', 'verbose_name_plural': 'ط³ط¬ظ„ط§طھ ط§ظ„ط¥ط´ط¹ط§ط±ط§طھ'},
        ),
        migrations.AlterModelOptions(
            name='notificationsettings',
            options={'verbose_name': 'ط§ط¹ط¯ط§ط¯ط§طھ ط§ظ„ط§ط´ط¹ط§ط±ط§طھ', 'verbose_name_plural': 'ط§ط¹ط¯ط§ط¯ط§طھ ط§ظ„ط§ط´ط¹ط§ط±ط§طھ'},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'verbose_name': 'ط¯ظپط¹ط© ظ…ط§ظ„ظٹط©', 'verbose_name_plural': 'ط§ظ„ط¯ظپط¹ط§طھ ط§ظ„ظ…ط§ظ„ظٹط©'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'طµظ†ظپ / ظ…ظ†طھط¬', 'verbose_name_plural': 'ط¯ظ„ظٹظ„ ط§ظ„ط£طµظ†ط§ظپ ظˆط§ظ„ظ…ظ†طھط¬ط§طھ'},
        ),
        migrations.AlterModelOptions(
            name='purchaseinvoice',
            options={'verbose_name': 'ظپط§طھظˆط±ط© ظ…ط´طھط±ظٹط§طھ', 'verbose_name_plural': 'ظپظˆط§طھظٹط± ط§ظ„ظ…ط´طھط±ظٹط§طھ'},
        ),
        migrations.AlterModelOptions(
            name='purchaseitem',
            options={'verbose_name': 'ط¨ظ†ط¯ ظ…ط´طھط±ظٹط§طھ', 'verbose_name_plural': 'ط¨ظ†ظˆط¯ ط§ظ„ظ…ط´طھط±ظٹط§طھ'},
        ),
        migrations.AlterModelOptions(
            name='repairpartused',
            options={'verbose_name': 'ظ‚ط·ط¹ط© ط؛ظٹط§ط± ظ…ط³طھظ‡ظ„ظƒط©', 'verbose_name_plural': 'ظ‚ط·ط¹ ط§ظ„ط؛ظٹط§ط± ط§ظ„ظ…ط³طھظ‡ظ„ظƒط© ظپظٹ ط§ظ„طµظٹط§ظ†ط©'},
        ),
        migrations.AlterModelOptions(
            name='repairticket',
            options={'verbose_name': 'طھط°ظƒط±ط© طµظٹط§ظ†ط©', 'verbose_name_plural': 'طھط°ط§ظƒط± ط§ظ„طµظٹط§ظ†ط©'},
        ),
        migrations.AlterModelOptions(
            name='saleinvoice',
            options={'verbose_name': 'ظپط§طھظˆط±ط© ظ…ط¨ظٹط¹ط§طھ', 'verbose_name_plural': 'ظپظˆط§طھظٹط± ط§ظ„ظ…ط¨ظٹط¹ط§طھ'},
        ),
        migrations.AlterModelOptions(
            name='saleitem',
            options={'verbose_name': 'ط¨ظ†ط¯ ظ…ط¨ظٹط¹ط§طھ', 'verbose_name_plural': 'ط¨ظ†ظˆط¯ ط§ظ„ظ…ط¨ظٹط¹ط§طھ'},
        ),
        migrations.AlterModelOptions(
            name='stock',
            options={'verbose_name': 'ظƒظ…ظٹط© ظ…ط®ط²ظˆظ†', 'verbose_name_plural': 'ظƒظ…ظٹط§طھ ط§ظ„ظ…ط®ط²ظˆظ†'},
        ),
        migrations.AlterModelOptions(
            name='stocktransfer',
            options={'verbose_name': 'ط\xadط±ظƒط© طھط\xadظˆظٹظ„ ظ…ط®ط²ظ†', 'verbose_name_plural': 'ط\xadط±ظƒط§طھ طھط\xadظˆظٹظ„ ط§ظ„ظ…ط®ط§ط²ظ†'},
        ),
        migrations.AlterModelOptions(
            name='stocktransferitem',
            options={'verbose_name': 'ط¨ظ†ط¯ طھط\xadظˆظٹظ„ ظ…ط®ط²ظ†', 'verbose_name_plural': 'ط¨ظ†ظˆط¯ طھط\xadظˆظٹظ„ ط§ظ„ظ…ط®ط§ط²ظ†'},
        ),
        migrations.AlterModelOptions(
            name='storesetting',
            options={'verbose_name': 'ط¥ط¹ط¯ط§ط¯ط§طھ ط§ظ„ظ…طھط¬ط±', 'verbose_name_plural': 'ط¥ط¹ط¯ط§ط¯ط§طھ ط§ظ„ظ…طھط¬ط±'},
        ),
        migrations.AlterModelOptions(
            name='treasury',
            options={'verbose_name': 'ط®ط²ظٹظ†ط©', 'verbose_name_plural': 'ط§ظ„ط®ط²ظ†'},
        ),
        migrations.AlterModelOptions(
            name='warehouse',
            options={'verbose_name': 'ظ…ط®ط²ظ† / ظپط±ط¹', 'verbose_name_plural': 'ط§ظ„ظ…ط®ط§ط²ظ† ظˆط§ظ„ظپط±ظˆط¹'},
        ),
        migrations.AlterModelOptions(
            name='warranty',
            options={'verbose_name': 'ط¶ظ…ط§ظ† ط¬ظ‡ط§ط²', 'verbose_name_plural': 'ط§ظ„ط¶ظ…ط§ظ†ط§طھ'},
        ),
        migrations.AddField(
            model_name='cashshift',
            name='treasury',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='shifts', to='erp.treasury', verbose_name='ط§ظ„ط®ط²ظٹظ†ط©'),
        ),
        migrations.AlterField(
            model_name='cashshift',
            name='actual_cash',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='ط§ظ„ط±طµظٹط¯ ط§ظ„ظپط¹ظ„ظٹ ط§ظ„ظ…ط³ظ„ظ…'),
        ),
        migrations.AlterField(
            model_name='cashshift',
            name='cashier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='ط§ظ„ظƒط§ط´ظٹط±'),
        ),
        migrations.AlterField(
            model_name='cashshift',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='ظˆظ‚طھ ط¥ط؛ظ„ط§ظ‚ ط§ظ„ظˆط±ط¯ظٹط©'),
        ),
        migrations.AlterField(
            model_name='cashshift',
            name='expected_closing_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='ط§ظ„ط±طµظٹط¯ ط§ظ„ظ†ظ‚ط¯ظٹ ط§ظ„ظ…طھظˆظ‚ط¹'),
        ),
        migrations.AlterField(
            model_name='cashshift',
            name='opening_balance',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='ط±طµظٹط¯ ط§ظ„ط¨ط¯ط§ظٹط©'),
        ),
        migrations.AlterField(
            model_name='cashshift',
            name='start_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='ظˆظ‚طھ ظپطھط\xad ط§ظ„ظˆط±ط¯ظٹط©'),
        ),
        migrations.AlterField(
            model_name='cashshift',
            name='status',
            field=models.CharField(choices=[('open', 'ظ…ظپطھظˆط\xadط©'), ('closed', 'ظ…ط؛ظ„ظ‚ط©')], default='open', max_length=20, verbose_name='ط\xadط§ظ„ط© ط§ظ„ظˆط±ط¯ظٹط©'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='ط§ظ„ط¹ظ†ظˆط§ظ†'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='contact_type',
            field=models.CharField(choices=[('customer', 'ط¹ظ…ظٹظ„'), ('supplier', 'ظ…ظˆط±ط¯ ط´ط±ظƒط§طھ'), ('used_seller', 'ط¨ط§ط¦ط¹ ط£ط¬ظ‡ط²ط© ظ…ط³طھط¹ظ…ظ„ط© (ظپط±ط¯)')], max_length=20, verbose_name='ظ†ظˆط¹ ط¬ظ‡ط© ط§ظ„ط§طھطµط§ظ„'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(max_length=255, verbose_name='ط§ظ„ط§ط³ظ…'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='national_id',
            field=models.CharField(blank=True, max_length=14, null=True, validators=[django.core.validators.RegexValidator(message='ط§ظ„ط±ظ‚ظ… ط§ظ„ظ‚ظˆظ…ظٹ ظٹط¬ط¨ ط£ظ† ظٹطھظƒظˆظ† ظ…ظ† 14 ط±ظ‚ظ…ط§ظ‹ ظپظ‚ط·.', regex='^\\d{14}$')], verbose_name='ط§ظ„ط±ظ‚ظ… ط§ظ„ظ‚ظˆظ…ظٹ'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='ط±ظ‚ظ… ط§ظ„ظ‡ط§طھظپ ظٹط¬ط¨ ط£ظ† ظٹطھظƒظˆظ† ظ…ظ† 11 ط±ظ‚ظ…ط§ظ‹ ظپظ‚ط·.', regex='^\\d{11}$')], verbose_name='ط±ظ‚ظ… ط§ظ„ظ‡ط§طھظپ'),
        ),
        migrations.AlterField(
            model_name='device',
            name='condition',
            field=models.CharField(choices=[('new', 'ط¬ط¯ظٹط¯'), ('used', 'ظ…ط³طھط¹ظ…ظ„')], max_length=20, verbose_name='ط§ظ„ط\xadط§ظ„ط©'),
        ),
        migrations.AlterField(
            model_name='device',
            name='cost',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='طھظƒظ„ظپط© ط§ظ„ط´ط±ط§ط،'),
        ),
        migrations.AlterField(
            model_name='device',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='طھط§ط±ظٹط® ط§ظ„ط¥ط¯ط®ط§ظ„'),
        ),
        migrations.AlterField(
            model_name='device',
            name='has_box',
            field=models.BooleanField(default=False, verbose_name='ظٹظˆط¬ط¯ ظƒط±طھظˆظ†ط©'),
        ),
        migrations.AlterField(
            model_name='device',
            name='has_charger',
            field=models.BooleanField(default=False, verbose_name='ظٹظˆط¬ط¯ ط´ط§ط\xadظ†'),
        ),
        migrations.AlterField(
            model_name='device',
            name='imei',
            field=models.CharField(max_length=50, unique=True, verbose_name='ط§ظ„ط³ظٹط±ظٹط§ظ„/IMEI 1'),
        ),
        migrations.AlterField(
            model_name='device',
            name='imei2',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='ط§ظ„ط³ظٹط±ظٹط§ظ„ 2/IMEI 2'),
        ),
        migrations.AlterField(
            model_name='device',
            name='is_sold',
            field=models.BooleanField(default=False, verbose_name='ظ…ط¨ط§ط¹طں'),
        ),
        migrations.AlterField(
            model_name='device',
            name='is_tax_paid',
            field=models.BooleanField(default=False, verbose_name='ط®ط§ظ„طµ ط§ظ„ط¶ط±ظٹط¨ط©'),
        ),
        migrations.AlterField(
            model_name='device',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='ظ…ظ„ط§ط\xadط¸ط§طھ ط§ظ„ط¬ظ‡ط§ط²'),
        ),
        migrations.AlterField(
            model_name='device',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.product', verbose_name='ط§ظ„ظ…ظˆط¯ظٹظ„/ط§ظ„طµظ†ظپ'),
        ),
        migrations.AlterField(
            model_name='device',
            name='purchased_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='erp.contact', verbose_name='طھظ… ط§ظ„ط´ط±ط§ط، ظ…ظ† (ظ„ظ„ظ…ط³طھط¹ظ…ظ„)'),
        ),
        migrations.AlterField(
            model_name='device',
            name='ram',
            field=models.CharField(blank=True, choices=[('3', '3 ط±ط§ظ…'), ('4', '4 ط±ط§ظ…'), ('6', '6 ط±ط§ظ…'), ('8', '8 ط±ط§ظ…'), ('12', '12 ط±ط§ظ…'), ('other', 'ط£ط®ط±ظ‰')], max_length=20, null=True, verbose_name='ط§ظ„ط±ط§ظ…'),
        ),
        migrations.AlterField(
            model_name='device',
            name='storage',
            field=models.CharField(blank=True, choices=[('128', '128 ط¬ظٹط¬ط§'), ('256', '256 ط¬ظٹط¬ط§'), ('512', '512 ط¬ظٹط¬ط§'), ('1gb', '1 ط¬ظٹط¬ط§'), ('1tb', '1 طھظٹط±ط§'), ('other', 'ط£ط®ط±ظ‰')], max_length=20, null=True, verbose_name='ط§ظ„ظ…ط³ط§ط\xadط©'),
        ),
        migrations.AlterField(
            model_name='device',
            name='used_status',
            field=models.CharField(blank=True, choices=[('like_new', 'ظƒط³ط± ط²ظٹط±ظˆ'), ('good_condition', 'ظ…ط³طھط¹ظ…ظ„ ط¨ط\xadط§ظ„ط© ط¬ظٹط¯ط©'), ('other', 'ط£ط®ط±ظ‰')], max_length=20, null=True, verbose_name='ط\xadط§ظ„ط© ط§ظ„ط¬ظ‡ط§ط² ط§ظ„ظ…ط³طھط¹ظ…ظ„'),
        ),
        migrations.AlterField(
            model_name='device',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.warehouse', verbose_name='ط§ظ„ظ…ط®ط²ظ† ط§ظ„ط\xadط§ظ„ظٹ'),
        ),
        migrations.AlterField(
            model_name='deviceattachment',
            name='attachment_type',
            field=models.CharField(blank=True, choices=[('id_front', 'طµظˆط±ط© ط§ظ„ط¨ط·ط§ظ‚ط© - ظˆط¬ظ‡'), ('id_back', 'طµظˆط±ط© ط§ظ„ط¨ط·ط§ظ‚ط© - ط¸ظ‡ط±'), ('contract', 'ط¹ظ‚ط¯ ظ…ط¨ط§ظٹط¹ط© / ط¥ظ‚ط±ط§ط± طھظ†ط§ط²ظ„'), ('device_condition', 'طµظˆط±ط© ظ„ط\xadط§ظ„ط© ط§ظ„ط¬ظ‡ط§ط²'), ('other', 'ط£ط®ط±ظ‰')], max_length=20, null=True, verbose_name='ظ†ظˆط¹ ط§ظ„ظ…ط±ظپظ‚'),
        ),
        migrations.AlterField(
            model_name='deviceattachment',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='used_devices_docs/%Y/%m/', verbose_name='ط§ظ„طµظˆط±ط©'),
        ),
        migrations.AlterField(
            model_name='deviceattachment',
            name='notes',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ظ…ظ„ط§ط\xadط¸ط§طھ'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='ط§ظ„ظ…ط¨ظ„ط؛'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp.expensecategory', verbose_name='ط¨ظ†ط¯ ط§ظ„ظ…طµط±ظˆظپ'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ط§ظ„طھظپط§طµظٹظ„/ط§ظ„ظˆطµظپ'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='shift',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='erp.cashshift', verbose_name='ط§ظ„ظˆط±ط¯ظٹط©'),
        ),
        migrations.AlterField(
            model_name='expensecategory',
            name='name',
            field=models.CharField(max_length=100, verbose_name='ط¨ظ†ط¯ ط§ظ„ظ…طµط±ظˆظپ'),
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.contact', verbose_name='ط§ظ„ط¹ظ…ظٹظ„'),
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='error_message',
            field=models.TextField(blank=True, null=True, verbose_name='ط±ط³ط§ظ„ط© ط§ظ„ط®ط·ط£'),
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='message_body',
            field=models.TextField(verbose_name='ظ…ط\xadطھظˆظ‰ ط§ظ„ط±ط³ط§ظ„ط©'),
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='notification_type',
            field=models.CharField(choices=[('whatsapp', 'ظˆط§طھط³ط§ط¨'), ('sms', 'SMS')], default='whatsapp', max_length=20, verbose_name='ظ†ظˆط¹ ط§ظ„ط¥ط´ط¹ط§ط±'),
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='retry_count',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='ط¹ط¯ط¯ ط§ظ„ظ…ط\xadط§ظˆظ„ط§طھ'),
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='sent_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='ظˆظ‚طھ ط§ظ„ط¥ط±ط³ط§ظ„'),
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='status',
            field=models.CharField(choices=[('queued', 'ظپظٹ ط§ظ„ط§ظ†طھط¸ط§ط±'), ('sent', 'طھظ… ط§ظ„ط¥ط±ط³ط§ظ„'), ('failed', 'ظپط´ظ„ ط§ظ„ط¥ط±ط³ط§ظ„'), ('skipped', 'طھظ… ط§ظ„طھط®ط·ظٹ (ظ…ط؛ظ„ظ‚)')], default='queued', max_length=20, verbose_name='ط§ظ„ط\xadط§ظ„ط©'),
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='ticket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='erp.repairticket', verbose_name='طھط°ظƒط±ط© ط§ظ„طµظٹط§ظ†ط©'),
        ),
        migrations.AlterField(
            model_name='notificationsettings',
            name='branch_name',
            field=models.CharField(default='ط§ظ„ظ…ط\xadظ„', help_text='ط³ظٹط¸ظ‡ط± ظپظٹ ظ†طµظˆطµ ط§ظ„ط±ط³ط§ط¦ظ„ طھظ„ظ‚ط§ط¦ظٹط§ظ‹.', max_length=100, verbose_name='ط§ط³ظ… ط§ظ„ظپط±ط¹ / ط§ظ„ظ…ط\xadظ„'),
        ),
        migrations.AlterField(
            model_name='notificationsettings',
            name='delay_max_seconds',
            field=models.PositiveSmallIntegerField(default=45, verbose_name='ط§ظ„ط\xadط¯ ط§ظ„ط§ظ‚طµظ‰ ظ„ظ„طھط§ط®ظٹط± (ط«ط§ظ†ظٹط©)'),
        ),
        migrations.AlterField(
            model_name='notificationsettings',
            name='delay_min_seconds',
            field=models.PositiveSmallIntegerField(default=15, verbose_name='ط§ظ„ط\xadط¯ ط§ظ„ط§ط¯ظ†ظ‰ ظ„ظ„طھط§ط®ظٹط± (ط«ط§ظ†ظٹط©)'),
        ),
        migrations.AlterField(
            model_name='notificationsettings',
            name='msg_delivered',
            field=models.TextField(default='ط´ظƒط±ط§ظ‹ {customer_name} ط¹ظ„ظ‰ ط«ظ‚طھظƒ ظپظٹ {branch_name}. ط±ظ‚ظ… ط§ظ„طھط°ظƒط±ط©: #{ticket_id}', verbose_name='ظ‚ط§ظ„ط¨: طھظ… ط§ظ„طھط³ظ„ظٹظ…'),
        ),
        migrations.AlterField(
            model_name='notificationsettings',
            name='msg_delivered_enabled',
            field=models.BooleanField(default=False, verbose_name='ط§ط±ط³ط§ظ„ ط¹ظ†ط¯: طھظ… ط§ظ„طھط³ظ„ظٹظ…'),
        ),
        migrations.AlterField(
            model_name='notificationsettings',
            name='msg_done',
            field=models.TextField(default='ط¬ظ‡ط§ط²ظƒ {device_model} ط¬ط§ظ‡ط² ظ„ظ„ط§ط³طھظ„ط§ظ… ظ…ظ† {branch_name}! ط±ظ‚ظ… ط§ظ„طھط°ظƒط±ط©: #{ticket_id}. ظپظٹ ط§ظ†طھط¸ط§ط±ظƒ {customer_name}', verbose_name='ظ‚ط§ظ„ط¨: ط¬ط§ظ‡ط² ظ„ظ„طھط³ظ„ظٹظ…'),
        ),
        migrations.AlterField(
            model_name='notificationsettings',
            name='msg_done_enabled',
            field=models.BooleanField(default=True, verbose_name='ط§ط±ط³ط§ظ„ ط¹ظ†ط¯: ط¬ط§ظ‡ط² ظ„ظ„طھط³ظ„ظٹظ…'),
        ),
        migrations.AlterField(
            model_name='notificationsettings',
            name='msg_in_progress',
            field=models.TextField(default='ط§ظ‡ظ„ط§ظ‹ {customer_name}طŒ ط¨ط¯ط£ ظپط±ظٹظ‚ظ†ط§ ط§ظ„ط¹ظ…ظ„ ط¹ظ„ظ‰ ط¬ظ‡ط§ط²ظƒ {device_model}. ط±ظ‚ظ… ط§ظ„طھط°ظƒط±ط©: #{ticket_id} â€” {branch_name}', verbose_name='ظ‚ط§ظ„ط¨: ط¬ط§ط±ظٹ ط§ظ„ط¹ظ…ظ„'),
        ),
        migrations.AlterField(
            model_name='notificationsettings',
            name='msg_in_progress_enabled',
            field=models.BooleanField(default=True, verbose_name='ط§ط±ط³ط§ظ„ ط¹ظ†ط¯: ط¬ط§ط±ظٹ ط§ظ„ط¹ظ…ظ„'),
        ),
        migrations.AlterField(
            model_name='notificationsettings',
            name='msg_pending',
            field=models.TextField(default='ط§ظ‡ظ„ط§ظ‹ {customer_name}طŒ طھظ… ط§ط³طھظ„ط§ظ… ط¬ظ‡ط§ط²ظƒ {device_model} ظپظٹ {branch_name}. ط±ظ‚ظ… طھط°ظƒط±طھظƒ: #{ticket_id}', verbose_name='ظ‚ط§ظ„ط¨: ظ‚ظٹط¯ ط§ظ„ط§ظ†طھط¸ط§ط±'),
        ),
        migrations.AlterField(
            model_name='notificationsettings',
            name='msg_pending_enabled',
            field=models.BooleanField(default=False, verbose_name='ط§ط±ط³ط§ظ„ ط¹ظ†ط¯: ظ‚ظٹط¯ ط§ظ„ط§ظ†طھط¸ط§ط±'),
        ),
        migrations.AlterField(
            model_name='notificationsettings',
            name='msg_waiting_parts',
            field=models.TextField(default='ط§ظ‡ظ„ط§ظ‹ {customer_name}طŒ ط¬ظ‡ط§ط²ظƒ {device_model} ظٹط\xadطھط§ط¬ ظ‚ط·ط¹ط© ط؛ظٹط§ط± ظ‚ظٹط¯ ط§ظ„طھظˆظپظٹط±. ط³ظ†ط¨ظ„ط؛ظƒ ظپظˆط± ط§ظ„ط§ظ†طھظ‡ط§ط،. ط±ظ‚ظ… ط§ظ„طھط°ظƒط±ط©: #{ticket_id}', verbose_name='ظ‚ط§ظ„ط¨: ط§ظ†طھط¸ط§ط± ظ‚ط·ط¹ ط§ظ„ط؛ظٹط§ط±'),
        ),
        migrations.AlterField(
            model_name='notificationsettings',
            name='msg_waiting_parts_enabled',
            field=models.BooleanField(default=True, verbose_name='ط§ط±ط³ط§ظ„ ط¹ظ†ط¯: ط§ظ†طھط¸ط§ط± ظ‚ط·ط¹ ط§ظ„ط؛ظٹط§ط±'),
        ),
        migrations.AlterField(
            model_name='notificationsettings',
            name='sender_phone',
            field=models.CharField(blank=True, help_text='ط§ظ„طµظٹط؛ط© ط§ظ„ط¯ظˆظ„ظٹط© ظ…ط«ط§ظ„: +201012345678', max_length=20, null=True, verbose_name='ط±ظ‚ظ… ط§ظ„ظˆط§طھط³ط§ط¨ ط§ظ„ظ…ط±ط³ظ„'),
        ),
        migrations.AlterField(
            model_name='notificationsettings',
            name='whatsapp_enabled',
            field=models.BooleanField(default=False, help_text='ظپط¹ظ‘ظ„ ظپظ‚ط· ط¨ط¹ط¯ ظ…ط³ط\xad QR Code ظˆط±ط¨ط· ط§ظ„ظ‡ط§طھظپ ط¨ط§ظ„ط³ظٹط±ظپط±.', verbose_name='طھظپط¹ظٹظ„ ط¥ط´ط¹ط§ط±ط§طھ ط§ظ„ظˆط§طھط³ط§ط¨'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='ط§ظ„ظ…ط¨ظ„ط؛'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='erp.saleinvoice', verbose_name='ط§ظ„ظپط§طھظˆط±ط©'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'ظ†ظ‚ط¯ظٹ'), ('visa', 'ظپظٹط²ط§'), ('wallet', 'ظ…ط\xadظپط¸ط© ط¥ظ„ظƒطھط±ظˆظ†ظٹط©')], max_length=20, verbose_name='ط·ط±ظٹظ‚ط© ط§ظ„ط¯ظپط¹'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ط±ظ‚ظ… ط§ظ„ظ…ط¹ط§ظ…ظ„ط©'),
        ),
        migrations.AlterField(
            model_name='product',
            name='average_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='ظ…طھظˆط³ط· ط§ظ„طھظƒظ„ظپط©'),
        ),
        migrations.AlterField(
            model_name='product',
            name='barcode_qr',
            field=models.CharField(max_length=100, unique=True, verbose_name='ط§ظ„ط¨ط§ط±ظƒظˆط¯ / QR'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=255, verbose_name='ط§ط³ظ… ط§ظ„طµظ†ظپ'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('phone', 'ظ…ظˆط¨ط§ظٹظ„'), ('accessory', 'ط¥ظƒط³ط³ظˆط§ط±'), ('spare_part', 'ظ‚ط·ط¹ط© ط؛ظٹط§ط±')], max_length=20, verbose_name='ظ†ظˆط¹ ط§ظ„طµظ†ظپ'),
        ),
        migrations.AlterField(
            model_name='product',
            name='requires_imei',
            field=models.BooleanField(default=False, verbose_name='ظٹطھط·ظ„ط¨ ط³ظٹط±ظٹط§ظ„/IMEI'),
        ),
        migrations.AlterField(
            model_name='product',
            name='selling_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='ط³ط¹ط± ط§ظ„ط¨ظٹط¹'),
        ),
        migrations.AlterField(
            model_name='purchaseinvoice',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='ظ…ط³طھظ„ظ… ط§ظ„ط¨ط¶ط§ط¹ط©'),
        ),
        migrations.AlterField(
            model_name='purchaseinvoice',
            name='deduction_addition_tax',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='ط¶ط±ظٹط¨ط© ط§ظ„ط®طµظ… ظˆط§ظ„ط¥ط¶ط§ظپط©'),
        ),
        migrations.AlterField(
            model_name='purchaseinvoice',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='ط§ظ„ط®طµظ…'),
        ),
        migrations.AlterField(
            model_name='purchaseinvoice',
            name='invoice_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='طھط§ط±ظٹط® ط§ظ„ظپط§طھظˆط±ط©'),
        ),
        migrations.AlterField(
            model_name='purchaseinvoice',
            name='net_amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='ط§ظ„طµط§ظپظٹ ظ„ظ„ط¯ظپط¹'),
        ),
        migrations.AlterField(
            model_name='purchaseinvoice',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='ط§ظ„ظ…ط¨ظ„ط؛ ط§ظ„ظ…ط¯ظپظˆط¹'),
        ),
        migrations.AlterField(
            model_name='purchaseinvoice',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'ظ†ظ‚ط¯ظٹ (ظƒط§ط´)'), ('credit', 'ط¢ط¬ظ„ ط¨ط§ظ„ظƒط§ظ…ظ„'), ('partial', 'ظ…ط³ط¯ط¯ ط¬ط²ط¦ظٹط§ظ‹')], default='cash', max_length=20, verbose_name='ط·ط±ظٹظ‚ط© ط§ظ„ط¯ظپط¹'),
        ),
        migrations.AlterField(
            model_name='purchaseinvoice',
            name='supplier',
            field=models.ForeignKey(limit_choices_to={'contact_type': 'supplier'}, on_delete=django.db.models.deletion.PROTECT, to='erp.contact', verbose_name='ط§ظ„ظ…ظˆط±ط¯'),
        ),
        migrations.AlterField(
            model_name='purchaseinvoice',
            name='supplier_invoice_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ط±ظ‚ظ… ظپط§طھظˆط±ط© ط§ظ„ظ…ظˆط±ط¯'),
        ),
        migrations.AlterField(
            model_name='purchaseinvoice',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='ط§ظ„ط¥ط¬ظ…ط§ظ„ظٹ'),
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='imei_list',
            field=models.TextField(blank=True, help_text='ظ„ظ„ط³ظٹط±ظٹط§ظ„ط§طھ ظ…ظپطµظˆظ„ط© ط¨ظپط§طµظ„ط©', null=True, verbose_name='ظ‚ط§ط¦ظ…ط© ط§ظ„ط³ظٹط±ظٹط§ظ„ط§طھ/IMEI'),
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='erp.purchaseinvoice', verbose_name='ظپط§طھظˆط±ط© ط§ظ„ط´ط±ط§ط،'),
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='is_tax_paid',
            field=models.BooleanField(default=False, verbose_name='ط®ط§ظ„طµ ط§ظ„ط¶ط±ظٹط¨ط©'),
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp.product', verbose_name='ط§ظ„طµظ†ظپ'),
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='quantity',
            field=models.IntegerField(verbose_name='ط§ظ„ظƒظ…ظٹط©'),
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='ram',
            field=models.CharField(blank=True, choices=[('3', '3 ط±ط§ظ…'), ('4', '4 ط±ط§ظ…'), ('6', '6 ط±ط§ظ…'), ('8', '8 ط±ط§ظ…'), ('12', '12 ط±ط§ظ…'), ('other', 'ط£ط®ط±ظ‰')], max_length=20, null=True, verbose_name='ط§ظ„ط±ط§ظ…'),
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='storage',
            field=models.CharField(blank=True, choices=[('128', '128 ط¬ظٹط¬ط§'), ('256', '256 ط¬ظٹط¬ط§'), ('512', '512 ط¬ظٹط¬ط§'), ('1gb', '1 ط¬ظٹط¬ط§'), ('1tb', '1 طھظٹط±ط§'), ('other', 'ط£ط®ط±ظ‰')], max_length=20, null=True, verbose_name='ط§ظ„ظ…ط³ط§ط\xadط©'),
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='unit_cost',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='طھظƒظ„ظپط© ط§ظ„ظˆط\xadط¯ط©'),
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp.warehouse', verbose_name='ط§ظ„ظ…ط®ط²ظ†'),
        ),
        migrations.AlterField(
            model_name='repairpartused',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='ط³ط¹ط± ط§ظ„ط¨ظٹط¹'),
        ),
        migrations.AlterField(
            model_name='repairpartused',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp.product', verbose_name='ظ‚ط·ط¹ط© ط§ظ„ط؛ظٹط§ط±'),
        ),
        migrations.AlterField(
            model_name='repairpartused',
            name='quantity',
            field=models.IntegerField(default=1, verbose_name='ط§ظ„ظƒظ…ظٹط©'),
        ),
        migrations.AlterField(
            model_name='repairpartused',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts_used', to='erp.repairticket', verbose_name='ط§ظ„طھط°ظƒط±ط©'),
        ),
        migrations.AlterField(
            model_name='repairpartused',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp.warehouse', verbose_name='ظ…ط®ط²ظ† ط§ظ„ط³ط\xadط¨'),
        ),
        migrations.AlterField(
            model_name='repairticket',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='طھط§ط±ظٹط® ط§ظ„ط¯ط®ظˆظ„'),
        ),
        migrations.AlterField(
            model_name='repairticket',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.contact', verbose_name='ط§ظ„ط¹ظ…ظٹظ„'),
        ),
        migrations.AlterField(
            model_name='repairticket',
            name='device_imei',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ط§ظ„ط³ظٹط±ظٹط§ظ„/IMEI'),
        ),
        migrations.AlterField(
            model_name='repairticket',
            name='device_model',
            field=models.CharField(max_length=100, verbose_name='ظ…ظˆط¯ظٹظ„ ط§ظ„ط¬ظ‡ط§ط²'),
        ),
        migrations.AlterField(
            model_name='repairticket',
            name='estimated_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='ط§ظ„طھظƒظ„ظپط© ط§ظ„طھظ‚ط¯ظٹط±ظٹط©'),
        ),
        migrations.AlterField(
            model_name='repairticket',
            name='issue_description',
            field=models.TextField(verbose_name='ظˆطµظپ ط§ظ„ط¹ط·ظ„'),
        ),
        migrations.AlterField(
            model_name='repairticket',
            name='labor_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='ظ…طµظ†ط¹ظٹط©'),
        ),
        migrations.AlterField(
            model_name='repairticket',
            name='status',
            field=models.CharField(choices=[('pending', 'ظ‚ظٹط¯ ط§ظ„ط§ظ†طھط¸ط§ط±'), ('in_progress', 'ط¬ط§ط±ظٹ ط§ظ„ط¹ظ…ظ„'), ('waiting_parts', 'ظپظٹ ط§ظ†طھط¸ط§ط± ظ‚ط·ط¹ ط§ظ„ط؛ظٹط§ط±'), ('done', 'ط¬ط§ظ‡ط² ظ„ظ„طھط³ظ„ظٹظ…'), ('delivered', 'طھظ… ط§ظ„طھط³ظ„ظٹظ…')], default='pending', max_length=20, verbose_name='ط\xadط§ظ„ط© ط§ظ„طھط°ظƒط±ط©'),
        ),
        migrations.AlterField(
            model_name='repairticket',
            name='technician',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='ط§ظ„ظپظ†ظٹ ط§ظ„ظ…ط®طھطµ'),
        ),
        migrations.AlterField(
            model_name='saleinvoice',
            name='cashier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='ط§ظ„ظƒط§ط´ظٹط±'),
        ),
        migrations.AlterField(
            model_name='saleinvoice',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp.contact', verbose_name='ط§ظ„ط¹ظ…ظٹظ„'),
        ),
        migrations.AlterField(
            model_name='saleinvoice',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='طھط§ط±ظٹط® ط§ظ„ظپط§طھظˆط±ط©'),
        ),
        migrations.AlterField(
            model_name='saleinvoice',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='ط§ظ„ط®طµظ…'),
        ),
        migrations.AlterField(
            model_name='saleinvoice',
            name='net_amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='ط§ظ„طµط§ظپظٹ'),
        ),
        migrations.AlterField(
            model_name='saleinvoice',
            name='shift',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp.cashshift', verbose_name='ط§ظ„ظˆط±ط¯ظٹط©'),
        ),
        migrations.AlterField(
            model_name='saleinvoice',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='ط§ظ„ط¥ط¬ظ…ط§ظ„ظٹ'),
        ),
        migrations.AlterField(
            model_name='saleinvoice',
            name='trade_in_value',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='ظ‚ظٹظ…ط© ط§ظ„ط§ط³طھط¨ط¯ط§ظ„'),
        ),
        migrations.AlterField(
            model_name='saleinvoice',
            name='traded_in_device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='traded_in_invoice', to='erp.device', verbose_name='ط§ظ„ط¬ظ‡ط§ط² ط§ظ„ظ…ط³طھط¨ط¯ظ„'),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='erp.device', verbose_name='ط¬ظ‡ط§ط² ظ…ظˆط¨ط§ظٹظ„'),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='erp.saleinvoice', verbose_name='ط§ظ„ظپط§طھظˆط±ط©'),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp.product', verbose_name='ط§ظ„طµظ†ظپ'),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='quantity',
            field=models.IntegerField(default=1, verbose_name='ط§ظ„ظƒظ…ظٹط©'),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='ط³ط¹ط± ط§ظ„ظˆط\xadط¯ط©'),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp.warehouse', verbose_name='ط§ظ„ظ…ط®ط²ظ†'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.product', verbose_name='ط§ظ„طµظ†ظپ'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='quantity',
            field=models.IntegerField(default=0, verbose_name='ط§ظ„ظƒظ…ظٹط©'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.warehouse', verbose_name='ط§ظ„ظ…ط®ط²ظ†'),
        ),
        migrations.AlterField(
            model_name='stocktransfer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='طھط§ط±ظٹط® ط§ظ„طھط\xadظˆظٹظ„'),
        ),
        migrations.AlterField(
            model_name='stocktransfer',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_created', to=settings.AUTH_USER_MODEL, verbose_name='ظ…ظ†ط´ط¦ ط§ظ„طھط\xadظˆظٹظ„'),
        ),
        migrations.AlterField(
            model_name='stocktransfer',
            name='from_warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_out', to='erp.warehouse', verbose_name='ظ…ظ† ظ…ط®ط²ظ†'),
        ),
        migrations.AlterField(
            model_name='stocktransfer',
            name='status',
            field=models.CharField(choices=[('pending', 'ظ‚ظٹط¯ ط§ظ„ظ†ظ‚ظ„'), ('completed', 'طھظ… ط§ظ„ط§ط³طھظ„ط§ظ…')], default='pending', max_length=20, verbose_name='ط\xadط§ظ„ط© ط§ظ„طھط\xadظˆظٹظ„'),
        ),
        migrations.AlterField(
            model_name='stocktransfer',
            name='to_warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_in', to='erp.warehouse', verbose_name='ط¥ظ„ظ‰ ظ…ط®ط²ظ†'),
        ),
        migrations.AlterField(
            model_name='stocktransferitem',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='erp.device', verbose_name='ط¬ظ‡ط§ط² ظ…ظˆط¨ط§ظٹظ„'),
        ),
        migrations.AlterField(
            model_name='stocktransferitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp.product', verbose_name='ط§ظ„طµظ†ظپ'),
        ),
        migrations.AlterField(
            model_name='stocktransferitem',
            name='quantity',
            field=models.IntegerField(default=1, verbose_name='ط§ظ„ظƒظ…ظٹط©'),
        ),
        migrations.AlterField(
            model_name='stocktransferitem',
            name='transfer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='erp.stocktransfer', verbose_name='ط\xadط±ظƒط© ط§ظ„طھط\xadظˆظٹظ„'),
        ),
        migrations.AlterField(
            model_name='storesetting',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='store_assets/', verbose_name='ط´ط¹ط§ط± ط§ظ„ظ…ط\xadظ„'),
        ),
        migrations.AlterField(
            model_name='storesetting',
            name='receipt_footer',
            field=models.TextField(blank=True, verbose_name='طھط°ظٹظٹظ„ ط§ظ„ظپط§طھظˆط±ط©'),
        ),
        migrations.AlterField(
            model_name='storesetting',
            name='receipt_header',
            field=models.TextField(blank=True, verbose_name='طھط±ظˆظٹط³ط© ط§ظ„ظپط§طھظˆط±ط©'),
        ),
        migrations.AlterField(
            model_name='storesetting',
            name='sms_api_key',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ظ…ظپطھط§ط\xad API ط§ظ„ط±ط³ط§ط¦ظ„ ط§ظ„ظ†طµظٹط©'),
        ),
        migrations.AlterField(
            model_name='storesetting',
            name='store_name',
            field=models.CharField(max_length=255, verbose_name='ط§ط³ظ… ط§ظ„ظ…ط\xadظ„'),
        ),
        migrations.AlterField(
            model_name='storesetting',
            name='whatsapp_api_key',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ظ…ظپطھط§ط\xad API ط§ظ„ظˆط§طھط³ط§ط¨'),
        ),
        migrations.AlterField(
            model_name='treasury',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='ط§ظ„ط±طµظٹط¯ ط§ظ„ط\xadط§ظ„ظٹ'),
        ),
        migrations.AlterField(
            model_name='treasury',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='طھط§ط±ظٹط® ط§ظ„ط¥ظ†ط´ط§ط،'),
        ),
        migrations.AlterField(
            model_name='treasury',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='ظ†ط´ط·ط©'),
        ),
        migrations.AlterField(
            model_name='treasury',
            name='name',
            field=models.CharField(max_length=100, verbose_name='ط§ط³ظ… ط§ظ„ط®ط²ظٹظ†ط©'),
        ),
        migrations.AlterField(
            model_name='treasury',
            name='opening_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='ط±طµظٹط¯ ط£ظˆظ„ ط§ظ„ظ…ط¯ط©'),
        ),
        migrations.AlterField(
            model_name='treasury',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='treasuries', to=settings.AUTH_USER_MODEL, verbose_name='ط§ظ„ظ…ط³طھط®ط¯ظ… ط§ظ„ظ…ط³ط¤ظˆظ„'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='ظ†ط´ط·'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='name',
            field=models.CharField(max_length=100, verbose_name='ط§ط³ظ… ط§ظ„ظ…ط®ط²ظ† / ط§ظ„ظپط±ط¹'),
        ),
        migrations.AlterField(
            model_name='warranty',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.contact', verbose_name='ط§ظ„ط¹ظ…ظٹظ„'),
        ),
        migrations.AlterField(
            model_name='warranty',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.device', verbose_name='ط§ظ„ط¬ظ‡ط§ط²'),
        ),
        migrations.AlterField(
            model_name='warranty',
            name='duration_days',
            field=models.IntegerField(default=14, verbose_name='ظ…ط¯ط© ط§ظ„ط¶ظ…ط§ظ† (ط¨ط§ظ„ط£ظٹط§ظ…)'),
        ),
        migrations.AlterField(
            model_name='warranty',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.saleinvoice', verbose_name='ظپط§طھظˆط±ط© ط§ظ„ط¨ظٹط¹'),
        ),
        migrations.AlterField(
            model_name='warranty',
            name='start_date',
            field=models.DateField(auto_now_add=True, verbose_name='طھط§ط±ظٹط® ط¨ط¯ط، ط§ظ„ط¶ظ…ط§ظ†'),
        ),
    ]
