# Generated by Django 6.0.6 on 2026-06-23 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0014_alter_cashshift_options_alter_contact_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseinvoice',
            name='treasury',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_invoices', to='erp.treasury', verbose_name='ط§ظ„ط®ط²ظٹظ†ط© ط§ظ„ظ…ط³ط¯ط¯ ط¹ظ„ظٹظ‡ط§'),
        ),
    ]
