# Generated by Django 6.0.6 on 2026-06-23 14:46

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0015_purchaseinvoice_treasury'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cashshift',
            options={'verbose_name': 'وردية خزينة', 'verbose_name_plural': 'ورديات الخزينة'},
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'جهة اتصال', 'verbose_name_plural': 'جهات الاتصال'},
        ),
        migrations.AlterModelOptions(
            name='device',
            options={'verbose_name': 'جهاز موبايل', 'verbose_name_plural': 'الأجهزة'},
        ),
        migrations.AlterModelOptions(
            name='deviceattachment',
            options={'verbose_name': 'مرفق جهاز', 'verbose_name_plural': 'مرفقات الأجهزة'},
        ),
        migrations.AlterModelOptions(
            name='expense',
            options={'verbose_name': 'مصروف تشغيلي', 'verbose_name_plural': 'المصروفات التشغيلية'},
        ),
        migrations.AlterModelOptions(
            name='expensecategory',
            options={'verbose_name': 'تصنيف مصروف', 'verbose_name_plural': 'تصنيفات المصروفات'},
        ),
        migrations.AlterModelOptions(
            name='notificationlog',
            options={'ordering': ['-sent_at'], 'verbose_name': 'سجل إشعار', 'verbose_name_plural': 'سجلات الإشعارات'},
        ),
        migrations.AlterModelOptions(
            name='notificationsettings',
            options={'verbose_name': 'اعدادات الاشعارات', 'verbose_name_plural': 'اعدادات الاشعارات'},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'verbose_name': 'دفعة مالية', 'verbose_name_plural': 'الدفعات المالية'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'صنف / منتج', 'verbose_name_plural': 'دليل الأصناف والمنتجات'},
        ),
        migrations.AlterModelOptions(
            name='purchaseinvoice',
            options={'verbose_name': 'فاتورة مشتريات', 'verbose_name_plural': 'فواتير المشتريات'},
        ),
        migrations.AlterModelOptions(
            name='purchaseitem',
            options={'verbose_name': 'بند مشتريات', 'verbose_name_plural': 'بنود المشتريات'},
        ),
        migrations.AlterModelOptions(
            name='repairpartused',
            options={'verbose_name': 'قطعة غيار مستهلكة', 'verbose_name_plural': 'قطع الغيار المستهلكة في الصيانة'},
        ),
        migrations.AlterModelOptions(
            name='repairticket',
            options={'verbose_name': 'تذكرة صيانة', 'verbose_name_plural': 'تذاكر الصيانة'},
        ),
        migrations.AlterModelOptions(
            name='saleinvoice',
            options={'verbose_name': 'فاتورة مبيعات', 'verbose_name_plural': 'فواتير المبيعات'},
        ),
        migrations.AlterModelOptions(
            name='saleitem',
            options={'verbose_name': 'بند مبيعات', 'verbose_name_plural': 'بنود المبيعات'},
        ),
        migrations.AlterModelOptions(
            name='stock',
            options={'verbose_name': 'كمية مخزون', 'verbose_name_plural': 'كميات المخزون'},
        ),
        migrations.AlterModelOptions(
            name='stocktransfer',
            options={'verbose_name': 'حركة تحويل مخزن', 'verbose_name_plural': 'حركات تحويل المخازن'},
        ),
        migrations.AlterModelOptions(
            name='stocktransferitem',
            options={'verbose_name': 'بند تحويل مخزن', 'verbose_name_plural': 'بنود تحويل المخازن'},
        ),
        migrations.AlterModelOptions(
            name='storesetting',
            options={'verbose_name': 'إعدادات المتجر', 'verbose_name_plural': 'إعدادات المتجر'},
        ),
        migrations.AlterModelOptions(
            name='treasury',
            options={'verbose_name': 'خزينة', 'verbose_name_plural': 'الخزن'},
        ),
        migrations.AlterModelOptions(
            name='warehouse',
            options={'verbose_name': 'مخزن / فرع', 'verbose_name_plural': 'المخازن والفروع'},
        ),
        migrations.AlterModelOptions(
            name='warranty',
            options={'verbose_name': 'ضمان جهاز', 'verbose_name_plural': 'الضمانات'},
        ),
        migrations.AddField(
            model_name='saleinvoice',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='المبلغ المدفوع'),
        ),
        migrations.AddField(
            model_name='saleinvoice',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'نقدي (كاش)'), ('credit', 'آجل بالكامل'), ('partial', 'مسدد جزئياً')], default='cash', max_length=20, verbose_name='طريقة الدفع'),
        ),
        migrations.AlterField(
            model_name='cashshift',
            name='actual_cash',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='الرصيد الفعلي المسلم'),
        ),
        migrations.AlterField(
            model_name='cashshift',
            name='cashier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='الكاشير'),
        ),
        migrations.AlterField(
            model_name='cashshift',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='وقت إغلاق الوردية'),
        ),
        migrations.AlterField(
            model_name='cashshift',
            name='expected_closing_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='الرصيد النقدي المتوقع'),
        ),
        migrations.AlterField(
            model_name='cashshift',
            name='opening_balance',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='رصيد البداية'),
        ),
        migrations.AlterField(
            model_name='cashshift',
            name='start_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='وقت فتح الوردية'),
        ),
        migrations.AlterField(
            model_name='cashshift',
            name='status',
            field=models.CharField(choices=[('open', 'مفتوحة'), ('closed', 'مغلقة')], default='open', max_length=20, verbose_name='حالة الوردية'),
        ),
        migrations.AlterField(
            model_name='cashshift',
            name='treasury',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='shifts', to='erp.treasury', verbose_name='الخزينة'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='العنوان'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='contact_type',
            field=models.CharField(choices=[('customer', 'عميل'), ('supplier', 'مورد شركات'), ('used_seller', 'بائع أجهزة مستعملة (فرد)')], max_length=20, verbose_name='نوع جهة الاتصال'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(max_length=255, verbose_name='الاسم'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='national_id',
            field=models.CharField(blank=True, max_length=14, null=True, validators=[django.core.validators.RegexValidator(message='الرقم القومي يجب أن يتكون من 14 رقماً فقط.', regex='^\\d{14}$')], verbose_name='الرقم القومي'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='رقم الهاتف يجب أن يتكون من 11 رقماً فقط.', regex='^\\d{11}$')], verbose_name='رقم الهاتف'),
        ),
        migrations.AlterField(
            model_name='device',
            name='condition',
            field=models.CharField(choices=[('new', 'جديد'), ('used', 'مستعمل')], max_length=20, verbose_name='الحالة'),
        ),
        migrations.AlterField(
            model_name='device',
            name='cost',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='تكلفة الشراء'),
        ),
        migrations.AlterField(
            model_name='device',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاريخ الإدخال'),
        ),
        migrations.AlterField(
            model_name='device',
            name='has_box',
            field=models.BooleanField(default=False, verbose_name='يوجد كرتونة'),
        ),
        migrations.AlterField(
            model_name='device',
            name='has_charger',
            field=models.BooleanField(default=False, verbose_name='يوجد شاحن'),
        ),
        migrations.AlterField(
            model_name='device',
            name='imei',
            field=models.CharField(max_length=50, unique=True, verbose_name='السيريال/IMEI 1'),
        ),
        migrations.AlterField(
            model_name='device',
            name='imei2',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='السيريال 2/IMEI 2'),
        ),
        migrations.AlterField(
            model_name='device',
            name='is_sold',
            field=models.BooleanField(default=False, verbose_name='مباع؟'),
        ),
        migrations.AlterField(
            model_name='device',
            name='is_tax_paid',
            field=models.BooleanField(default=False, verbose_name='خالص الضريبة'),
        ),
        migrations.AlterField(
            model_name='device',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='ملاحظات الجهاز'),
        ),
        migrations.AlterField(
            model_name='device',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.product', verbose_name='الموديل/الصنف'),
        ),
        migrations.AlterField(
            model_name='device',
            name='purchased_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='erp.contact', verbose_name='تم الشراء من (للمستعمل)'),
        ),
        migrations.AlterField(
            model_name='device',
            name='ram',
            field=models.CharField(blank=True, choices=[('3', '3 رام'), ('4', '4 رام'), ('6', '6 رام'), ('8', '8 رام'), ('12', '12 رام'), ('other', 'أخرى')], max_length=20, null=True, verbose_name='الرام'),
        ),
        migrations.AlterField(
            model_name='device',
            name='storage',
            field=models.CharField(blank=True, choices=[('128', '128 جيجا'), ('256', '256 جيجا'), ('512', '512 جيجا'), ('1gb', '1 جيجا'), ('1tb', '1 تيرا'), ('other', 'أخرى')], max_length=20, null=True, verbose_name='المساحة'),
        ),
        migrations.AlterField(
            model_name='device',
            name='used_status',
            field=models.CharField(blank=True, choices=[('like_new', 'كسر زيرو'), ('good_condition', 'مستعمل بحالة جيدة'), ('other', 'أخرى')], max_length=20, null=True, verbose_name='حالة الجهاز المستعمل'),
        ),
        migrations.AlterField(
            model_name='device',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.warehouse', verbose_name='المخزن الحالي'),
        ),
        migrations.AlterField(
            model_name='deviceattachment',
            name='attachment_type',
            field=models.CharField(blank=True, choices=[('id_front', 'صورة البطاقة - وجه'), ('id_back', 'صورة البطاقة - ظهر'), ('contract', 'عقد مبايعة / إقرار تنازل'), ('device_condition', 'صورة لحالة الجهاز'), ('other', 'أخرى')], max_length=20, null=True, verbose_name='نوع المرفق'),
        ),
        migrations.AlterField(
            model_name='deviceattachment',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='used_devices_docs/%Y/%m/', verbose_name='الصورة'),
        ),
        migrations.AlterField(
            model_name='deviceattachment',
            name='notes',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ملاحظات'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='المبلغ'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp.expensecategory', verbose_name='بند المصروف'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='التفاصيل/الوصف'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='shift',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='erp.cashshift', verbose_name='الوردية'),
        ),
        migrations.AlterField(
            model_name='expensecategory',
            name='name',
            field=models.CharField(max_length=100, verbose_name='بند المصروف'),
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.contact', verbose_name='العميل'),
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='error_message',
            field=models.TextField(blank=True, null=True, verbose_name='رسالة الخطأ'),
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='message_body',
            field=models.TextField(verbose_name='محتوى الرسالة'),
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='notification_type',
            field=models.CharField(choices=[('whatsapp', 'واتساب'), ('sms', 'SMS')], default='whatsapp', max_length=20, verbose_name='نوع الإشعار'),
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='retry_count',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='عدد المحاولات'),
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='sent_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='وقت الإرسال'),
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='status',
            field=models.CharField(choices=[('queued', 'في الانتظار'), ('sent', 'تم الإرسال'), ('failed', 'فشل الإرسال'), ('skipped', 'تم التخطي (مغلق)')], default='queued', max_length=20, verbose_name='الحالة'),
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='ticket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='erp.repairticket', verbose_name='تذكرة الصيانة'),
        ),
        migrations.AlterField(
            model_name='notificationsettings',
            name='branch_name',
            field=models.CharField(default='المحل', help_text='سيظهر في نصوص الرسائل تلقائياً.', max_length=100, verbose_name='اسم الفرع / المحل'),
        ),
        migrations.AlterField(
            model_name='notificationsettings',
            name='delay_max_seconds',
            field=models.PositiveSmallIntegerField(default=45, verbose_name='الحد الاقصى للتاخير (ثانية)'),
        ),
        migrations.AlterField(
            model_name='notificationsettings',
            name='delay_min_seconds',
            field=models.PositiveSmallIntegerField(default=15, verbose_name='الحد الادنى للتاخير (ثانية)'),
        ),
        migrations.AlterField(
            model_name='notificationsettings',
            name='msg_delivered',
            field=models.TextField(default='شكراً {customer_name} على ثقتك في {branch_name}. رقم التذكرة: #{ticket_id}', verbose_name='قالب: تم التسليم'),
        ),
        migrations.AlterField(
            model_name='notificationsettings',
            name='msg_delivered_enabled',
            field=models.BooleanField(default=False, verbose_name='ارسال عند: تم التسليم'),
        ),
        migrations.AlterField(
            model_name='notificationsettings',
            name='msg_done',
            field=models.TextField(default='جهازك {device_model} جاهز للاستلام من {branch_name}! رقم التذكرة: #{ticket_id}. في انتظارك {customer_name}', verbose_name='قالب: جاهز للتسليم'),
        ),
        migrations.AlterField(
            model_name='notificationsettings',
            name='msg_done_enabled',
            field=models.BooleanField(default=True, verbose_name='ارسال عند: جاهز للتسليم'),
        ),
        migrations.AlterField(
            model_name='notificationsettings',
            name='msg_in_progress',
            field=models.TextField(default='اهلاً {customer_name}، بدأ فريقنا العمل على جهازك {device_model}. رقم التذكرة: #{ticket_id} — {branch_name}', verbose_name='قالب: جاري العمل'),
        ),
        migrations.AlterField(
            model_name='notificationsettings',
            name='msg_in_progress_enabled',
            field=models.BooleanField(default=True, verbose_name='ارسال عند: جاري العمل'),
        ),
        migrations.AlterField(
            model_name='notificationsettings',
            name='msg_pending',
            field=models.TextField(default='اهلاً {customer_name}، تم استلام جهازك {device_model} في {branch_name}. رقم تذكرتك: #{ticket_id}', verbose_name='قالب: قيد الانتظار'),
        ),
        migrations.AlterField(
            model_name='notificationsettings',
            name='msg_pending_enabled',
            field=models.BooleanField(default=False, verbose_name='ارسال عند: قيد الانتظار'),
        ),
        migrations.AlterField(
            model_name='notificationsettings',
            name='msg_waiting_parts',
            field=models.TextField(default='اهلاً {customer_name}، جهازك {device_model} يحتاج قطعة غيار قيد التوفير. سنبلغك فور الانتهاء. رقم التذكرة: #{ticket_id}', verbose_name='قالب: انتظار قطع الغيار'),
        ),
        migrations.AlterField(
            model_name='notificationsettings',
            name='msg_waiting_parts_enabled',
            field=models.BooleanField(default=True, verbose_name='ارسال عند: انتظار قطع الغيار'),
        ),
        migrations.AlterField(
            model_name='notificationsettings',
            name='sender_phone',
            field=models.CharField(blank=True, help_text='الصيغة الدولية مثال: +201012345678', max_length=20, null=True, verbose_name='رقم الواتساب المرسل'),
        ),
        migrations.AlterField(
            model_name='notificationsettings',
            name='whatsapp_enabled',
            field=models.BooleanField(default=False, help_text='فعّل فقط بعد مسح QR Code وربط الهاتف بالسيرفر.', verbose_name='تفعيل إشعارات الواتساب'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='المبلغ'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='erp.saleinvoice', verbose_name='الفاتورة'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'نقدي'), ('visa', 'فيزا'), ('wallet', 'محفظة إلكترونية')], max_length=20, verbose_name='طريقة الدفع'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='رقم المعاملة'),
        ),
        migrations.AlterField(
            model_name='product',
            name='average_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='متوسط التكلفة'),
        ),
        migrations.AlterField(
            model_name='product',
            name='barcode_qr',
            field=models.CharField(max_length=100, unique=True, verbose_name='الباركود / QR'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=255, verbose_name='اسم الصنف'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('phone', 'موبايل'), ('accessory', 'إكسسوار'), ('spare_part', 'قطعة غيار')], max_length=20, verbose_name='نوع الصنف'),
        ),
        migrations.AlterField(
            model_name='product',
            name='requires_imei',
            field=models.BooleanField(default=False, verbose_name='يتطلب سيريال/IMEI'),
        ),
        migrations.AlterField(
            model_name='product',
            name='selling_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='سعر البيع'),
        ),
        migrations.AlterField(
            model_name='purchaseinvoice',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='مستلم البضاعة'),
        ),
        migrations.AlterField(
            model_name='purchaseinvoice',
            name='deduction_addition_tax',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='ضريبة الخصم والإضافة'),
        ),
        migrations.AlterField(
            model_name='purchaseinvoice',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='الخصم'),
        ),
        migrations.AlterField(
            model_name='purchaseinvoice',
            name='invoice_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الفاتورة'),
        ),
        migrations.AlterField(
            model_name='purchaseinvoice',
            name='net_amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='الصافي للدفع'),
        ),
        migrations.AlterField(
            model_name='purchaseinvoice',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='المبلغ المدفوع'),
        ),
        migrations.AlterField(
            model_name='purchaseinvoice',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'نقدي (كاش)'), ('credit', 'آجل بالكامل'), ('partial', 'مسدد جزئياً')], default='cash', max_length=20, verbose_name='طريقة الدفع'),
        ),
        migrations.AlterField(
            model_name='purchaseinvoice',
            name='supplier',
            field=models.ForeignKey(limit_choices_to={'contact_type': 'supplier'}, on_delete=django.db.models.deletion.PROTECT, to='erp.contact', verbose_name='المورد'),
        ),
        migrations.AlterField(
            model_name='purchaseinvoice',
            name='supplier_invoice_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='رقم فاتورة المورد'),
        ),
        migrations.AlterField(
            model_name='purchaseinvoice',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='الإجمالي'),
        ),
        migrations.AlterField(
            model_name='purchaseinvoice',
            name='treasury',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_invoices', to='erp.treasury', verbose_name='الخزينة المسدد عليها'),
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='imei_list',
            field=models.TextField(blank=True, help_text='للسيريالات مفصولة بفاصلة', null=True, verbose_name='قائمة السيريالات/IMEI'),
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='erp.purchaseinvoice', verbose_name='فاتورة الشراء'),
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='is_tax_paid',
            field=models.BooleanField(default=False, verbose_name='خالص الضريبة'),
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp.product', verbose_name='الصنف'),
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='quantity',
            field=models.IntegerField(verbose_name='الكمية'),
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='ram',
            field=models.CharField(blank=True, choices=[('3', '3 رام'), ('4', '4 رام'), ('6', '6 رام'), ('8', '8 رام'), ('12', '12 رام'), ('other', 'أخرى')], max_length=20, null=True, verbose_name='الرام'),
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='storage',
            field=models.CharField(blank=True, choices=[('128', '128 جيجا'), ('256', '256 جيجا'), ('512', '512 جيجا'), ('1gb', '1 جيجا'), ('1tb', '1 تيرا'), ('other', 'أخرى')], max_length=20, null=True, verbose_name='المساحة'),
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='unit_cost',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='تكلفة الوحدة'),
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp.warehouse', verbose_name='المخزن'),
        ),
        migrations.AlterField(
            model_name='repairpartused',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='سعر البيع'),
        ),
        migrations.AlterField(
            model_name='repairpartused',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp.product', verbose_name='قطعة الغيار'),
        ),
        migrations.AlterField(
            model_name='repairpartused',
            name='quantity',
            field=models.IntegerField(default=1, verbose_name='الكمية'),
        ),
        migrations.AlterField(
            model_name='repairpartused',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts_used', to='erp.repairticket', verbose_name='التذكرة'),
        ),
        migrations.AlterField(
            model_name='repairpartused',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp.warehouse', verbose_name='مخزن السحب'),
        ),
        migrations.AlterField(
            model_name='repairticket',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاريخ الدخول'),
        ),
        migrations.AlterField(
            model_name='repairticket',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.contact', verbose_name='العميل'),
        ),
        migrations.AlterField(
            model_name='repairticket',
            name='device_imei',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='السيريال/IMEI'),
        ),
        migrations.AlterField(
            model_name='repairticket',
            name='device_model',
            field=models.CharField(max_length=100, verbose_name='موديل الجهاز'),
        ),
        migrations.AlterField(
            model_name='repairticket',
            name='estimated_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='التكلفة التقديرية'),
        ),
        migrations.AlterField(
            model_name='repairticket',
            name='issue_description',
            field=models.TextField(verbose_name='وصف العطل'),
        ),
        migrations.AlterField(
            model_name='repairticket',
            name='labor_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='مصنعية'),
        ),
        migrations.AlterField(
            model_name='repairticket',
            name='status',
            field=models.CharField(choices=[('pending', 'قيد الانتظار'), ('in_progress', 'جاري العمل'), ('waiting_parts', 'في انتظار قطع الغيار'), ('done', 'جاهز للتسليم'), ('delivered', 'تم التسليم')], default='pending', max_length=20, verbose_name='حالة التذكرة'),
        ),
        migrations.AlterField(
            model_name='repairticket',
            name='technician',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='الفني المختص'),
        ),
        migrations.AlterField(
            model_name='saleinvoice',
            name='cashier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='الكاشير'),
        ),
        migrations.AlterField(
            model_name='saleinvoice',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp.contact', verbose_name='العميل'),
        ),
        migrations.AlterField(
            model_name='saleinvoice',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الفاتورة'),
        ),
        migrations.AlterField(
            model_name='saleinvoice',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='الخصم'),
        ),
        migrations.AlterField(
            model_name='saleinvoice',
            name='net_amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='الصافي'),
        ),
        migrations.AlterField(
            model_name='saleinvoice',
            name='shift',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp.cashshift', verbose_name='الوردية'),
        ),
        migrations.AlterField(
            model_name='saleinvoice',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='الإجمالي'),
        ),
        migrations.AlterField(
            model_name='saleinvoice',
            name='trade_in_value',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='قيمة الاستبدال'),
        ),
        migrations.AlterField(
            model_name='saleinvoice',
            name='traded_in_device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='traded_in_invoice', to='erp.device', verbose_name='الجهاز المستبدل'),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='erp.device', verbose_name='جهاز موبايل'),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='erp.saleinvoice', verbose_name='الفاتورة'),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp.product', verbose_name='الصنف'),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='quantity',
            field=models.IntegerField(default=1, verbose_name='الكمية'),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='سعر الوحدة'),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp.warehouse', verbose_name='المخزن'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.product', verbose_name='الصنف'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='quantity',
            field=models.IntegerField(default=0, verbose_name='الكمية'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.warehouse', verbose_name='المخزن'),
        ),
        migrations.AlterField(
            model_name='stocktransfer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ التحويل'),
        ),
        migrations.AlterField(
            model_name='stocktransfer',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_created', to=settings.AUTH_USER_MODEL, verbose_name='منشئ التحويل'),
        ),
        migrations.AlterField(
            model_name='stocktransfer',
            name='from_warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_out', to='erp.warehouse', verbose_name='من مخزن'),
        ),
        migrations.AlterField(
            model_name='stocktransfer',
            name='status',
            field=models.CharField(choices=[('pending', 'قيد النقل'), ('completed', 'تم الاستلام')], default='pending', max_length=20, verbose_name='حالة التحويل'),
        ),
        migrations.AlterField(
            model_name='stocktransfer',
            name='to_warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_in', to='erp.warehouse', verbose_name='إلى مخزن'),
        ),
        migrations.AlterField(
            model_name='stocktransferitem',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='erp.device', verbose_name='جهاز موبايل'),
        ),
        migrations.AlterField(
            model_name='stocktransferitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp.product', verbose_name='الصنف'),
        ),
        migrations.AlterField(
            model_name='stocktransferitem',
            name='quantity',
            field=models.IntegerField(default=1, verbose_name='الكمية'),
        ),
        migrations.AlterField(
            model_name='stocktransferitem',
            name='transfer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='erp.stocktransfer', verbose_name='حركة التحويل'),
        ),
        migrations.AlterField(
            model_name='storesetting',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='store_assets/', verbose_name='شعار المحل'),
        ),
        migrations.AlterField(
            model_name='storesetting',
            name='receipt_footer',
            field=models.TextField(blank=True, verbose_name='تذييل الفاتورة'),
        ),
        migrations.AlterField(
            model_name='storesetting',
            name='receipt_header',
            field=models.TextField(blank=True, verbose_name='ترويسة الفاتورة'),
        ),
        migrations.AlterField(
            model_name='storesetting',
            name='sms_api_key',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='مفتاح API الرسائل النصية'),
        ),
        migrations.AlterField(
            model_name='storesetting',
            name='store_name',
            field=models.CharField(max_length=255, verbose_name='اسم المحل'),
        ),
        migrations.AlterField(
            model_name='storesetting',
            name='whatsapp_api_key',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='مفتاح API الواتساب'),
        ),
        migrations.AlterField(
            model_name='treasury',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='الرصيد الحالي'),
        ),
        migrations.AlterField(
            model_name='treasury',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AlterField(
            model_name='treasury',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='نشطة'),
        ),
        migrations.AlterField(
            model_name='treasury',
            name='name',
            field=models.CharField(max_length=100, verbose_name='اسم الخزينة'),
        ),
        migrations.AlterField(
            model_name='treasury',
            name='opening_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='رصيد أول المدة'),
        ),
        migrations.AlterField(
            model_name='treasury',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='treasuries', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم المسؤول'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='نشط'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='name',
            field=models.CharField(max_length=100, verbose_name='اسم المخزن / الفرع'),
        ),
        migrations.AlterField(
            model_name='warranty',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.contact', verbose_name='العميل'),
        ),
        migrations.AlterField(
            model_name='warranty',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.device', verbose_name='الجهاز'),
        ),
        migrations.AlterField(
            model_name='warranty',
            name='duration_days',
            field=models.IntegerField(default=14, verbose_name='مدة الضمان (بالأيام)'),
        ),
        migrations.AlterField(
            model_name='warranty',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.saleinvoice', verbose_name='فاتورة البيع'),
        ),
        migrations.AlterField(
            model_name='warranty',
            name='start_date',
            field=models.DateField(auto_now_add=True, verbose_name='تاريخ بدء الضمان'),
        ),
    ]
