# Generated by Django 6.0.6 on 2026-06-23 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0016_alter_cashshift_options_alter_contact_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='opening_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='رصيد أول المدة'),
        ),
    ]
