# Generated by Django 6.0.6 on 2026-06-23 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0017_contact_opening_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='treasury',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='erp.treasury', verbose_name='الخزينة المنصرف منها'),
        ),
    ]
