# Generated by Django 6.0.6 on 2026-06-23 16:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0018_expense_treasury'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('receipt', 'سند قبض (استلام نقدية)'), ('payment', 'سند صرف (دفع نقدية)')], max_length=20, verbose_name='نوع الحركة')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='المبلغ')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='البيان')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='التاريخ')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.contact', verbose_name='جهة الاتصال')),
                ('treasury', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp.treasury', verbose_name='الخزينة')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'حركة حساب',
                'verbose_name_plural': 'حركات الحسابات',
            },
        ),
    ]
