# Generated by Django 6.0.6 on 2026-06-24 07:58

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0019_contacttransaction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='storesetting',
            name='allowed_radius',
            field=models.IntegerField(default=50, verbose_name='النطاق المسموح للبصمة (بالمتر)'),
        ),
        migrations.AddField(
            model_name='storesetting',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='خط العرض (Latitude) للمحل'),
        ),
        migrations.AddField(
            model_name='storesetting',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='خط الطول (Longitude) للمحل'),
        ),
        migrations.CreateModel(
            name='EmployeeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hourly_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='قيمة ساعة العمل العادية')),
                ('daily_working_hours', models.DecimalField(decimal_places=2, default=8.0, max_digits=4, verbose_name='ساعات العمل اليومية')),
                ('shift_start_time', models.TimeField(blank=True, null=True, verbose_name='ميعاد الحضور')),
                ('shift_end_time', models.TimeField(blank=True, null=True, verbose_name='ميعاد الانصراف')),
                ('deduction_per_hour', models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='قيمة الخصم للساعة')),
                ('overtime_per_hour', models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='قيمة الإضافي للساعة')),
                ('base_salary', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='الراتب الأساسي (اختياري)')),
                ('is_active', models.BooleanField(default=True, verbose_name='على رأس العمل')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee_profile', to=settings.AUTH_USER_MODEL, verbose_name='حساب المستخدم')),
            ],
            options={
                'verbose_name': 'ملف الموظف',
                'verbose_name_plural': 'ملفات الموظفين',
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='التاريخ')),
                ('check_in', models.DateTimeField(blank=True, null=True, verbose_name='وقت الحضور')),
                ('check_out', models.DateTimeField(blank=True, null=True, verbose_name='وقت الانصراف')),
                ('delay_hours', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='ساعات التأخير')),
                ('overtime_hours', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='الساعات الإضافية')),
                ('status', models.CharField(choices=[('present', 'حاضر'), ('absent', 'غائب'), ('leave', 'إجازة')], default='present', max_length=20, verbose_name='الحالة')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='erp.employeeprofile', verbose_name='الموظف')),
            ],
            options={
                'verbose_name': 'سجل حضور',
                'verbose_name_plural': 'سجلات الحضور والانصراف',
                'unique_together': {('employee', 'date')},
            },
        ),
        migrations.CreateModel(
            name='Payroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField(verbose_name='الشهر')),
                ('year', models.IntegerField(verbose_name='السنة')),
                ('total_worked_hours', models.DecimalField(decimal_places=2, default=0.0, max_digits=6, verbose_name='إجمالي ساعات العمل')),
                ('total_delay_hours', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='إجمالي ساعات التأخير')),
                ('total_overtime_hours', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='إجمالي الساعات الإضافية')),
                ('base_pay', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='المستحق الأساسي')),
                ('overtime_pay', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='مكافأة الإضافي')),
                ('deductions', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='إجمالي الخصومات')),
                ('net_salary', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='الراتب الصافي')),
                ('is_paid', models.BooleanField(default=False, verbose_name='تم الصرف')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الصرف')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payrolls', to='erp.employeeprofile', verbose_name='الموظف')),
            ],
            options={
                'verbose_name': 'مسير راتب',
                'verbose_name_plural': 'مسيرات الرواتب',
                'unique_together': {('employee', 'month', 'year')},
            },
        ),
    ]
