# Generated by Django 6.0.6 on 2026-06-24 08:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0020_storesetting_allowed_radius_storesetting_latitude_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ المرتجع')),
                ('refund_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='المبلغ المسترد من المورد')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='سبب الاسترجاع')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='بواسطة')),
                ('purchase_invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='returns', to='erp.purchaseinvoice', verbose_name='فاتورة الشراء الأصلية')),
                ('treasury', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp.treasury', verbose_name='الخزينة المودع بها')),
            ],
            options={
                'verbose_name': 'مرتجع مشتريات',
                'verbose_name_plural': 'مرتجعات المشتريات',
            },
        ),
        migrations.CreateModel(
            name='PurchaseReturnItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, verbose_name='الكمية المرتجعة')),
                ('purchase_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.purchaseitem', verbose_name='البند الأصلي')),
                ('return_invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='erp.purchasereturn', verbose_name='فاتورة المرتجع')),
            ],
            options={
                'verbose_name': 'بند مرتجع مشتريات',
                'verbose_name_plural': 'بنود مرتجعات المشتريات',
            },
        ),
        migrations.CreateModel(
            name='SaleReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ المرتجع')),
                ('refund_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='المبلغ المسترد للعميل')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='سبب الاسترجاع')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='بواسطة')),
                ('sale_invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='returns', to='erp.saleinvoice', verbose_name='فاتورة البيع الأصلية')),
                ('treasury', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp.treasury', verbose_name='الخزينة المخصوم منها')),
            ],
            options={
                'verbose_name': 'مرتجع مبيعات',
                'verbose_name_plural': 'مرتجعات المبيعات',
            },
        ),
        migrations.CreateModel(
            name='SaleReturnItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, verbose_name='الكمية المرتجعة')),
                ('return_invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='erp.salereturn', verbose_name='فاتورة المرتجع')),
                ('sale_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.saleitem', verbose_name='البند الأصلي')),
            ],
            options={
                'verbose_name': 'بند مرتجع مبيعات',
                'verbose_name_plural': 'بنود مرتجعات المبيعات',
            },
        ),
    ]
