# Generated by Django 6.0.6 on 2026-06-24 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0021_purchasereturn_purchasereturnitem_salereturn_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('phone', 'موبايل'), ('accessory', 'إكسسوار عام'), ('cover_screen', 'جراب + اسكرينة'), ('electrical', 'كهرباء'), ('spare_part', 'قطعة غيار')], max_length=20, verbose_name='نوع الصنف'),
        ),
    ]
