# Generated by Django 6.0.6 on 2026-06-24 17:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0022_alter_product_product_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TreasuryTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('in', 'إيداع / إيراد'), ('out', 'سحب / مصروف')], max_length=10, verbose_name='نوع الحركة')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='المبلغ')),
                ('description', models.CharField(max_length=255, verbose_name='البيان / الوصف')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ ووقت الحركة')),
                ('treasury', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='erp.treasury', verbose_name='الخزينة')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'حركة خزينة',
                'verbose_name_plural': 'حركات الخزينة',
                'ordering': ['-date'],
            },
        ),
    ]
