# Generated by Django 6.0.6 on 2026-06-24 17:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0023_treasurytransaction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommissionRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type', models.CharField(choices=[('phone', 'موبايل'), ('accessory', 'إكسسوار عام'), ('cover_screen', 'جراب + اسكرينة'), ('electrical', 'كهرباء'), ('spare_part', 'قطعة غيار')], max_length=20, unique=True, verbose_name='نوع الصنف')),
                ('sales_milestone', models.DecimalField(decimal_places=2, help_text='مثال: 1000', max_digits=10, verbose_name='شريحة المبيعات (ج.م)')),
                ('commission_amount', models.DecimalField(decimal_places=2, help_text='مثال: 5', max_digits=8, verbose_name='مبلغ العمولة المستحق (ج.م)')),
            ],
            options={
                'verbose_name': 'قاعدة عمولة',
                'verbose_name_plural': 'لائحة العمولات والمحققات',
            },
        ),
        migrations.CreateModel(
            name='SalesTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(choices=[('daily', 'يومي'), ('monthly', 'شهري'), ('yearly', 'سنوي')], max_length=10, verbose_name='الفترة')),
                ('target_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='قيمة التارجت المطلوب (ج.م)')),
                ('date', models.DateField(help_text='إذا كان يومي، اختر اليوم. إذا شهري، اختر أي يوم في الشهر المعني.', verbose_name='التاريخ المعني بالتارجت')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_targets', to=settings.AUTH_USER_MODEL, verbose_name='الكاشير (الموظف)')),
            ],
            options={
                'verbose_name': 'تارجت مبيعات',
                'verbose_name_plural': 'تارجت المبيعات (الأهداف)',
                'unique_together': {('user', 'period', 'date')},
            },
        ),
    ]
