# Generated by Django 6.0.6 on 2026-06-25 07:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0024_commissionrule_salestarget'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'إنشاء'), ('update', 'تعديل'), ('delete', 'حذف')], max_length=20, verbose_name='العملية')),
                ('model_name', models.CharField(max_length=100, verbose_name='النموذج / الجدول')),
                ('object_id', models.CharField(max_length=255, verbose_name='معرف العنصر')),
                ('object_repr', models.CharField(max_length=255, verbose_name='وصف العنصر')),
                ('changes', models.JSONField(blank=True, default=dict, null=True, verbose_name='التفاصيل / التغييرات')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ ووقت الحركة')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='عنوان الـ IP')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'سجل مراقبة',
                'verbose_name_plural': 'سجل النظام (Audit Log)',
                'ordering': ['-timestamp'],
            },
        ),
    ]
