# Generated by Django 6.0.6 on 2026-06-25 08:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0025_auditlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='GiftCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='كود البطاقة')),
                ('initial_balance', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='الرصيد الابتدائي')),
                ('current_balance', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='الرصيد الحالي')),
                ('is_active', models.BooleanField(default=True, verbose_name='مفعلة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإصدار')),
                ('expires_at', models.DateField(blank=True, null=True, verbose_name='تاريخ الانتهاء')),
            ],
            options={
                'verbose_name': 'بطاقة هدية',
                'verbose_name_plural': 'بطاقات الهدايا',
            },
        ),
        migrations.AddField(
            model_name='contact',
            name='loyalty_points',
            field=models.IntegerField(default=0, verbose_name='رصيد نقاط الولاء'),
        ),
        migrations.AddField(
            model_name='saleinvoice',
            name='gift_card_deduction',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='المخصوم من بطاقة الهدية'),
        ),
        migrations.AddField(
            model_name='saleinvoice',
            name='points_discount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='خصم النقاط المستبدلة'),
        ),
        migrations.AddField(
            model_name='saleinvoice',
            name='points_earned',
            field=models.IntegerField(default=0, verbose_name='نقاط مكتسبة'),
        ),
        migrations.AddField(
            model_name='saleinvoice',
            name='points_redeemed',
            field=models.IntegerField(default=0, verbose_name='نقاط مستبدلة'),
        ),
        migrations.AddField(
            model_name='storesetting',
            name='egp_per_100_points',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=10, verbose_name='قيمة الخصم لكل 100 نقطة مستبدلة'),
        ),
        migrations.AddField(
            model_name='storesetting',
            name='enable_loyalty_system',
            field=models.BooleanField(default=True, verbose_name='تفعيل نظام نقاط الولاء'),
        ),
        migrations.AddField(
            model_name='storesetting',
            name='loyalty_points_per_egp',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=10, verbose_name='عدد النقاط المكتسبة لكل جنيه'),
        ),
        migrations.AddField(
            model_name='saleinvoice',
            name='gift_card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='erp.giftcard', verbose_name='بطاقة الهدية المستخدمة'),
        ),
    ]
