# Generated by Django 6.0.6 on 2026-06-27 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0027_repairticket_parent_ticket_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='is_returned_to_seller',
            field=models.BooleanField(default=False, verbose_name='تم إرجاعه للبائع'),
        ),
        migrations.AddField(
            model_name='purchasereturn',
            name='debt_reduction',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='قيمة الخصم من المستحقات'),
        ),
        migrations.AddField(
            model_name='salereturn',
            name='debt_reduction',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='قيمة الخصم من المديونية'),
        ),
    ]
