# Generated by Django 6.0.6 on 2026-06-27 08:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0028_device_is_returned_to_seller_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم الفرع')),
                ('address', models.TextField(blank=True, null=True, verbose_name='عنوان الفرع')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='رقم الهاتف')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
            ],
            options={
                'verbose_name': 'فرع',
                'verbose_name_plural': 'الفروع',
            },
        ),
        migrations.AlterField(
            model_name='storesetting',
            name='store_name',
            field=models.CharField(max_length=255, verbose_name='اسم المحل (العلامة التجارية)'),
        ),
        migrations.AddField(
            model_name='storesetting',
            name='branch',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='store_setting', to='erp.branch', verbose_name='الفرع المرتبط'),
        ),
    ]
