# Generated by Django 6.0.6 on 2026-06-27 08:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0029_branch_alter_storesetting_store_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashshift',
            name='branch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='erp.branch', verbose_name='الفرع'),
        ),
        migrations.AddField(
            model_name='contact',
            name='branch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='erp.branch', verbose_name='الفرع'),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='active_branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_employees', to='erp.branch', verbose_name='الفرع النشط حالياً'),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='allowed_branches',
            field=models.ManyToManyField(blank=True, related_name='employees', to='erp.branch', verbose_name='الفروع المسموح بها'),
        ),
        migrations.AddField(
            model_name='expense',
            name='branch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='erp.branch', verbose_name='الفرع'),
        ),
        migrations.AddField(
            model_name='product',
            name='branch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='erp.branch', verbose_name='الفرع'),
        ),
        migrations.AddField(
            model_name='purchaseinvoice',
            name='branch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='erp.branch', verbose_name='الفرع'),
        ),
        migrations.AddField(
            model_name='repairticket',
            name='branch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='erp.branch', verbose_name='الفرع'),
        ),
        migrations.AddField(
            model_name='saleinvoice',
            name='branch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='erp.branch', verbose_name='الفرع'),
        ),
        migrations.AddField(
            model_name='treasury',
            name='branch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='erp.branch', verbose_name='الفرع'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='branch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='erp.branch', verbose_name='الفرع'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='name',
            field=models.CharField(max_length=100, verbose_name='اسم المخزن'),
        ),
    ]
