# Generated by Django 6.0.6 on 2026-07-02 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0030_cashshift_branch_contact_branch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='allowed_radius',
            field=models.IntegerField(default=50, verbose_name='النطاق المسموح للبصمة (بالمتر)'),
        ),
        migrations.AddField(
            model_name='branch',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='خط العرض (Latitude) للفرع'),
        ),
        migrations.AddField(
            model_name='branch',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='خط الطول (Longitude) للفرع'),
        ),
    ]
