# Generated by Django 6.0.6 on 2026-07-02 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='domain',
            options={'verbose_name': 'النطاق (Domain)', 'verbose_name_plural': 'النطاقات (Domains)'},
        ),
        migrations.AlterModelOptions(
            name='shop',
            options={'verbose_name': 'المتجر / الفرع', 'verbose_name_plural': 'المتاجر والفروع'},
        ),
    ]
